/*
 * ksepi.cnvendian.input.c
 *
 * This file is automatically generated by the 'createCnvEndianInput' script.
 * It contains the declarations of all CVs and TGT exports variables
 * and is used to generate the endian converters for all of these
 * variables.
 *
 * Generated on Mon Dec 23 09:41:38 PST 2019
 */

#include "ksepi.global.h"
#include "ksepi.allcv.h"
#include "ksepi.tgtex.h"
