/*
 * ksgre_tutorial.cnvendian.input.c
 *
 * This file is automatically generated by the 'createCnvEndianInput' script.
 * It contains the declarations of all CVs and TGT exports variables
 * and is used to generate the endian converters for all of these
 * variables.
 *
 * Generated on Fri Jun 28 13:30:50 PDT 2019
 */

#include "ksgre_tutorial.global.h"
#include "ksgre_tutorial.allcv.h"
#include "ksgre_tutorial.tgtex.h"
