#define cv_cnv_endian_char cnv_endian_char
#define cv_cnv_endian_signed_char cnv_endian_signed_char
#define cv_cnv_endian_unsigned_char cnv_endian_unsigned_char
#define cv_cnv_endian_short cnv_endian_short
#define cv_cnv_endian_signed_short cnv_endian_signed_short
#define cv_cnv_endian_unsigned_short cnv_endian_unsigned_short
#define cv_cnv_endian_int cnv_endian_int
#define cv_cnv_endian_signed_int cnv_endian_signed_int
#define cv_cnv_endian_unsigned_int cnv_endian_unsigned_int
#define cv_cnv_endian_long cnv_endian_long
#define cv_cnv_endian_signed_long cnv_endian_signed_long
#define cv_cnv_endian_unsigned_long cnv_endian_unsigned_long
#define cv_cnv_endian_long_long cnv_endian_long_long
#define cv_cnv_endian_signed_long_long cnv_endian_signed_long_long
#define cv_cnv_endian_unsigned_long_long cnv_endian_unsigned_long_long
#define cv_cnv_endian_float cnv_endian_float
#define cv_cnv_endian_double cnv_endian_double
#define cv_cnv_endian_long_double cnv_endian_long_double
#define cv_cnv_endian_void cnv_endian_void
#define cv_cnv_endian___builtin_va_list cnv_endian___builtin_va_list
#define cv_cnv_endian___gconv_trans_fct cnv_endian___gconv_trans_fct
#define cv_cnv_endian___gconv_trans_context_fct cnv_endian___gconv_trans_context_fct
#define cv_cnv_endian___gconv_trans_end_fct cnv_endian___gconv_trans_end_fct
#define cv_cnv_endian___gconv_fct cnv_endian___gconv_fct
#define cv_cnv_endian___gconv_btowc_fct cnv_endian___gconv_btowc_fct
#define cv_cnv_endian___gconv_init_fct cnv_endian___gconv_init_fct
#define cv_cnv_endian___gconv_end_fct cnv_endian___gconv_end_fct
#define cv_cnv_endian_struct___gconv_loaded_object cnv_endian_struct___gconv_loaded_object

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

extern void cnv_endian_reverse( int length, void *val );
extern void cnv_endian_char( void *_ecnv_target_ );
extern void cnv_endian_signed_char( void *_ecnv_target_ );
extern void cnv_endian_unsigned_char( void *_ecnv_target_ );
extern void cnv_endian_short( void *_ecnv_target_ );
extern void cnv_endian_signed_short( void *_ecnv_target_ );
extern void cnv_endian_unsigned_short( void *_ecnv_target_ );
extern void cnv_endian_int( void *_ecnv_target_ );
extern void cnv_endian_signed_int( void *_ecnv_target_ );
extern void cnv_endian_unsigned_int( void *_ecnv_target_ );
extern void cnv_endian_long( void *_ecnv_target_ );
extern void cnv_endian_signed_long( void *_ecnv_target_ );
extern void cnv_endian_unsigned_long( void *_ecnv_target_ );
extern void cnv_endian_long_long( void *_ecnv_target_ );
extern void cnv_endian_signed_long_long( void *_ecnv_target_ );
extern void cnv_endian_unsigned_long_long( void *_ecnv_target_ );
extern void cnv_endian_float( void *_ecnv_target_ );
extern void cnv_endian_double( void *_ecnv_target_ );
extern void cnv_endian_long_double( void *_ecnv_target_ );
extern void cnv_endian_void( void *_ecnv_target_ );
extern void cnv_endian___builtin_va_list( void *_ecnv_target_ );
extern void cnv_endian___gconv_trans_fct( void *_ecnv_target_ );
extern void cnv_endian___gconv_trans_context_fct( void *_ecnv_target_ );
extern void cnv_endian___gconv_trans_end_fct( void *_ecnv_target_ );
extern void cnv_endian___gconv_fct( void *_ecnv_target_ );
extern void cnv_endian___gconv_btowc_fct( void *_ecnv_target_ );
extern void cnv_endian___gconv_init_fct( void *_ecnv_target_ );
extern void cnv_endian___gconv_end_fct( void *_ecnv_target_ );
extern void cnv_endian_struct___gconv_loaded_object( void *_ecnv_target_ );

#ifdef __cplusplus
}
#endif /* __cplusplus */


#include "ksgre_tutorial.cnvendian.input.i"


/* Prototype Definitions */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

extern void cv_cnv_endian_ptrdiff_t( ptrdiff_t *_ecnv_target_ );
extern void cv_cnv_endian_size_t( size_t *_ecnv_target_ );
extern void cv_cnv_endian_wchar_t( wchar_t *_ecnv_target_ );
extern void cv_cnv_endian_int8_t( int8_t *_ecnv_target_ );
extern void cv_cnv_endian_int16_t( int16_t *_ecnv_target_ );
extern void cv_cnv_endian_int32_t( int32_t *_ecnv_target_ );
extern void cv_cnv_endian_int64_t( int64_t *_ecnv_target_ );
extern void cv_cnv_endian_uint8_t( uint8_t *_ecnv_target_ );
extern void cv_cnv_endian_uint16_t( uint16_t *_ecnv_target_ );
extern void cv_cnv_endian_uint32_t( uint32_t *_ecnv_target_ );
extern void cv_cnv_endian_uint64_t( uint64_t *_ecnv_target_ );
extern void cv_cnv_endian_int_least8_t( int_least8_t *_ecnv_target_ );
extern void cv_cnv_endian_int_least16_t( int_least16_t *_ecnv_target_ );
extern void cv_cnv_endian_int_least32_t( int_least32_t *_ecnv_target_ );
extern void cv_cnv_endian_int_least64_t( int_least64_t *_ecnv_target_ );
extern void cv_cnv_endian_uint_least8_t( uint_least8_t *_ecnv_target_ );
extern void cv_cnv_endian_uint_least16_t( uint_least16_t *_ecnv_target_ );
extern void cv_cnv_endian_uint_least32_t( uint_least32_t *_ecnv_target_ );
extern void cv_cnv_endian_uint_least64_t( uint_least64_t *_ecnv_target_ );
extern void cv_cnv_endian_int_fast8_t( int_fast8_t *_ecnv_target_ );
extern void cv_cnv_endian_int_fast16_t( int_fast16_t *_ecnv_target_ );
extern void cv_cnv_endian_int_fast32_t( int_fast32_t *_ecnv_target_ );
extern void cv_cnv_endian_int_fast64_t( int_fast64_t *_ecnv_target_ );
extern void cv_cnv_endian_uint_fast8_t( uint_fast8_t *_ecnv_target_ );
extern void cv_cnv_endian_uint_fast16_t( uint_fast16_t *_ecnv_target_ );
extern void cv_cnv_endian_uint_fast32_t( uint_fast32_t *_ecnv_target_ );
extern void cv_cnv_endian_uint_fast64_t( uint_fast64_t *_ecnv_target_ );
extern void cv_cnv_endian_intptr_t( intptr_t *_ecnv_target_ );
extern void cv_cnv_endian_uintptr_t( uintptr_t *_ecnv_target_ );
extern void cv_cnv_endian_intmax_t( intmax_t *_ecnv_target_ );
extern void cv_cnv_endian_uintmax_t( uintmax_t *_ecnv_target_ );
extern void cv_cnv_endian_s8( s8 *_ecnv_target_ );
extern void cv_cnv_endian_n8( n8 *_ecnv_target_ );
extern void cv_cnv_endian_s16( s16 *_ecnv_target_ );
extern void cv_cnv_endian_n16( n16 *_ecnv_target_ );
extern void cv_cnv_endian_s32( s32 *_ecnv_target_ );
extern void cv_cnv_endian_n32( n32 *_ecnv_target_ );
extern void cv_cnv_endian_s64( s64 *_ecnv_target_ );
extern void cv_cnv_endian_n64( n64 *_ecnv_target_ );
extern void cv_cnv_endian_f32( f32 *_ecnv_target_ );
extern void cv_cnv_endian_f64( f64 *_ecnv_target_ );
extern void cv_cnv_endian_struct_EXT_CERD_PARAMS( struct EXT_CERD_PARAMS *_ecnv_target_ );
extern void cv_cnv_endian_PSD_FILTER_GEN( PSD_FILTER_GEN *_ecnv_target_ );
extern void cv_cnv_endian_CPRM_ENTRY_TYPE( CPRM_ENTRY_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_CPRM_TYPE( CPRM_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_COIL_PORTS_RX_MAPS_TYPE( COIL_PORTS_RX_MAPS_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_struct_CTMEntry( struct CTMEntry *_ecnv_target_ );
extern void cv_cnv_endian_CTMEntryType( CTMEntryType *_ecnv_target_ );
extern void cv_cnv_endian_struct_QuadVolWeight( struct QuadVolWeight *_ecnv_target_ );
extern void cv_cnv_endian_QuadVolWeightType( QuadVolWeightType *_ecnv_target_ );
extern void cv_cnv_endian_struct_CTTEntry( struct CTTEntry *_ecnv_target_ );
extern void cv_cnv_endian_ChannelTransTableEntryType( ChannelTransTableEntryType *_ecnv_target_ );
extern void cv_cnv_endian_struct__INSTALL_COIL_INFO_( struct _INSTALL_COIL_INFO_ *_ecnv_target_ );
extern void cv_cnv_endian_INSTALL_COIL_INFO( INSTALL_COIL_INFO *_ecnv_target_ );
extern void cv_cnv_endian_struct__INSTALL_COIL_CONNECTOR_INFO_( struct _INSTALL_COIL_CONNECTOR_INFO_ *_ecnv_target_ );
extern void cv_cnv_endian_INSTALL_COIL_CONNECTOR_INFO( INSTALL_COIL_CONNECTOR_INFO *_ecnv_target_ );
extern void cv_cnv_endian_struct_coil_config_params( struct coil_config_params *_ecnv_target_ );
extern void cv_cnv_endian_COIL_CONFIG_PARAM_TYPE( COIL_CONFIG_PARAM_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_struct_application_config_param_type( struct application_config_param_type *_ecnv_target_ );
extern void cv_cnv_endian_APPLICATION_CONFIG_PARAM_TYPE( APPLICATION_CONFIG_PARAM_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_struct_application_config_hdr( struct application_config_hdr *_ecnv_target_ );
extern void cv_cnv_endian_APPLICATION_CONFIG_HDR( APPLICATION_CONFIG_HDR *_ecnv_target_ );
extern void cv_cnv_endian_COIL_INFO( COIL_INFO *_ecnv_target_ );
extern void cv_cnv_endian_TX_COIL_INFO( TX_COIL_INFO *_ecnv_target_ );
extern void cv_cnv_endian_struct__psd_coil_info_( struct _psd_coil_info_ *_ecnv_target_ );
extern void cv_cnv_endian_PSD_COIL_INFO( PSD_COIL_INFO *_ecnv_target_ );
extern void cv_cnv_endian_power_monitor_table_t( power_monitor_table_t *_ecnv_target_ );
extern void cv_cnv_endian_entry_point_table_t( entry_point_table_t *_ecnv_target_ );
extern void cv_cnv_endian_ENTRY_POINT_TABLE( ENTRY_POINT_TABLE *_ecnv_target_ );
extern void cv_cnv_endian_ENTRY_PNT_TABLE( ENTRY_PNT_TABLE *_ecnv_target_ );
extern void cv_cnv_endian_enum_ANATOMY_ATTRIBUTE( enum ANATOMY_ATTRIBUTE *_ecnv_target_ );
extern void cv_cnv_endian_ANATOMY_ATTRIBUTE_E( ANATOMY_ATTRIBUTE_E *_ecnv_target_ );
extern void cv_cnv_endian_enum_ANATOMY_ATTRIBUTE_CATEGORY( enum ANATOMY_ATTRIBUTE_CATEGORY *_ecnv_target_ );
extern void cv_cnv_endian_ANATOMY_ATTRIBUTE_CATEGORY_E( ANATOMY_ATTRIBUTE_CATEGORY_E *_ecnv_target_ );
extern void cv_cnv_endian_SCAN_INFO( SCAN_INFO *_ecnv_target_ );
extern void cv_cnv_endian_PSC_INFO( PSC_INFO *_ecnv_target_ );
extern void cv_cnv_endian_GIR_INFO( GIR_INFO *_ecnv_target_ );
extern void cv_cnv_endian_DATA_ACQ_ORDER( DATA_ACQ_ORDER *_ecnv_target_ );
extern void cv_cnv_endian_RSP_INFO( RSP_INFO *_ecnv_target_ );
extern void cv_cnv_endian_PHASE_OFF( PHASE_OFF *_ecnv_target_ );
extern void cv_cnv_endian_RSP_PSC_INFO( RSP_PSC_INFO *_ecnv_target_ );
extern void cv_cnv_endian_WF_PROCESSOR( WF_PROCESSOR *_ecnv_target_ );
extern void cv_cnv_endian_WF_HARDWARE_TYPE( WF_HARDWARE_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_HW_DIRECTION( HW_DIRECTION *_ecnv_target_ );
extern void cv_cnv_endian_SSP_S_ATTRIB( SSP_S_ATTRIB *_ecnv_target_ );
extern void cv_cnv_endian_PSD_EXIT_ARG( PSD_EXIT_ARG *_ecnv_target_ );
extern void cv_cnv_endian_enum_GRADIENT_COILS( enum GRADIENT_COILS *_ecnv_target_ );
extern void cv_cnv_endian_GRADIENT_COIL_E( GRADIENT_COIL_E *_ecnv_target_ );
extern void cv_cnv_endian_enum_BODY_COIL_TYPES( enum BODY_COIL_TYPES *_ecnv_target_ );
extern void cv_cnv_endian_BODY_COIL_TYPE_E( BODY_COIL_TYPE_E *_ecnv_target_ );
extern void cv_cnv_endian_enum_PSD_BOARD_TYPE( enum PSD_BOARD_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_PSD_BOARD_TYPE_E( PSD_BOARD_TYPE_E *_ecnv_target_ );
extern void cv_cnv_endian_enum_SSC_TYPE( enum SSC_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_SSC_TYPE_E( SSC_TYPE_E *_ecnv_target_ );
extern void cv_cnv_endian_enum_GRADIENT_COIL_METHOD( enum GRADIENT_COIL_METHOD *_ecnv_target_ );
extern void cv_cnv_endian_GRADIENT_COIL_METHOD_E( GRADIENT_COIL_METHOD_E *_ecnv_target_ );
extern void cv_cnv_endian_enum_POWER_IN_HEAT_CALC( enum POWER_IN_HEAT_CALC *_ecnv_target_ );
extern void cv_cnv_endian_POWER_IN_HEAT_CALC_E( POWER_IN_HEAT_CALC_E *_ecnv_target_ );
extern void cv_cnv_endian_enum_GRADIENT_PULSE_TYPE( enum GRADIENT_PULSE_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_GRADIENT_PULSE_TYPE_E( GRADIENT_PULSE_TYPE_E *_ecnv_target_ );
extern void cv_cnv_endian_GRAD_PULSE( GRAD_PULSE *_ecnv_target_ );
extern void cv_cnv_endian_RF_PULSE( RF_PULSE *_ecnv_target_ );
extern void cv_cnv_endian_RF_PULSE_INFO( RF_PULSE_INFO *_ecnv_target_ );
extern void cv_cnv_endian_regulatory_control_mode_e( regulatory_control_mode_e *_ecnv_target_ );
extern void cv_cnv_endian_enum_epic_slice_order_type_e( enum epic_slice_order_type_e *_ecnv_target_ );
extern void cv_cnv_endian_epic_slice_order_type( epic_slice_order_type *_ecnv_target_ );
extern void cv_cnv_endian_enum_exciter_type( enum exciter_type *_ecnv_target_ );
extern void cv_cnv_endian_exciterSelection( exciterSelection *_ecnv_target_ );
extern void cv_cnv_endian_enum_receiver_type( enum receiver_type *_ecnv_target_ );
extern void cv_cnv_endian_receiverSelection( receiverSelection *_ecnv_target_ );
extern void cv_cnv_endian_enum_oscillator_source( enum oscillator_source *_ecnv_target_ );
extern void cv_cnv_endian_demodSelection( demodSelection *_ecnv_target_ );
extern void cv_cnv_endian_enum_nav_type( enum nav_type *_ecnv_target_ );
extern void cv_cnv_endian_navSelection( navSelection *_ecnv_target_ );
extern void cv_cnv_endian_enum_VALUE_SYSTEM_TYPE( enum VALUE_SYSTEM_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_VALUE_SYSTEM_TYPE_E( VALUE_SYSTEM_TYPE_E *_ecnv_target_ );
extern void cv_cnv_endian_enum_PSD_PATIENT_ENTRY( enum PSD_PATIENT_ENTRY *_ecnv_target_ );
extern void cv_cnv_endian_PSD_PATIENT_ENTRY_E( PSD_PATIENT_ENTRY_E *_ecnv_target_ );
extern void cv_cnv_endian_enum_CAL_MODE( enum CAL_MODE *_ecnv_target_ );
extern void cv_cnv_endian_CAL_MODE_E( CAL_MODE_E *_ecnv_target_ );
extern void cv_cnv_endian_enum_RG_CAL_MODE( enum RG_CAL_MODE *_ecnv_target_ );
extern void cv_cnv_endian_RG_CAL_MODE_E( RG_CAL_MODE_E *_ecnv_target_ );
extern void cv_cnv_endian_enum_ADD_SCAN_TYPE( enum ADD_SCAN_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_ADD_SCAN_TYPE_E( ADD_SCAN_TYPE_E *_ecnv_target_ );
extern void cv_cnv_endian_enum_PSD_SLTHICK_LABEL( enum PSD_SLTHICK_LABEL *_ecnv_target_ );
extern void cv_cnv_endian_PSD_SLTHICK_LABEL_E( PSD_SLTHICK_LABEL_E *_ecnv_target_ );
extern void cv_cnv_endian_enum_PSD_NAV_TYPE( enum PSD_NAV_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_PSD_NAV_TYPE_E( PSD_NAV_TYPE_E *_ecnv_target_ );
extern void cv_cnv_endian_enum_PSD_FLIP_ANGLE_MODE_LABEL( enum PSD_FLIP_ANGLE_MODE_LABEL *_ecnv_target_ );
extern void cv_cnv_endian_PSD_FLIP_ANGLE_LABEL_E( PSD_FLIP_ANGLE_LABEL_E *_ecnv_target_ );
extern void cv_cnv_endian_enum_PSD_AUTO_TR_MODE_LABEL( enum PSD_AUTO_TR_MODE_LABEL *_ecnv_target_ );
extern void cv_cnv_endian_PSD_AUTO_TR_MODE_LABEL_E( PSD_AUTO_TR_MODE_LABEL_E *_ecnv_target_ );
extern void cv_cnv_endian_enum_CARDIAC_GATE_TYPE( enum CARDIAC_GATE_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_CARDIAC_GATE_TYPE_E( CARDIAC_GATE_TYPE_E *_ecnv_target_ );
extern void cv_cnv_endian_CHAR( CHAR *_ecnv_target_ );
extern void cv_cnv_endian_SHORT( SHORT *_ecnv_target_ );
extern void cv_cnv_endian_INT( INT *_ecnv_target_ );
extern void cv_cnv_endian_LONG( LONG *_ecnv_target_ );
extern void cv_cnv_endian_FLOAT( FLOAT *_ecnv_target_ );
extern void cv_cnv_endian_DOUBLE( DOUBLE *_ecnv_target_ );
extern void cv_cnv_endian_UCHAR( UCHAR *_ecnv_target_ );
extern void cv_cnv_endian_USHORT( USHORT *_ecnv_target_ );
extern void cv_cnv_endian_UINT( UINT *_ecnv_target_ );
extern void cv_cnv_endian_ULONG( ULONG *_ecnv_target_ );
extern void cv_cnv_endian_STATUS( STATUS *_ecnv_target_ );
extern void cv_cnv_endian_ADDRESS( ADDRESS *_ecnv_target_ );
extern void cv_cnv_endian_enum_e_axis( enum e_axis *_ecnv_target_ );
extern void cv_cnv_endian_t_axis( t_axis *_ecnv_target_ );
extern void cv_cnv_endian___u_char( __u_char *_ecnv_target_ );
extern void cv_cnv_endian___u_short( __u_short *_ecnv_target_ );
extern void cv_cnv_endian___u_int( __u_int *_ecnv_target_ );
extern void cv_cnv_endian___u_long( __u_long *_ecnv_target_ );
extern void cv_cnv_endian___int8_t( __int8_t *_ecnv_target_ );
extern void cv_cnv_endian___uint8_t( __uint8_t *_ecnv_target_ );
extern void cv_cnv_endian___int16_t( __int16_t *_ecnv_target_ );
extern void cv_cnv_endian___uint16_t( __uint16_t *_ecnv_target_ );
extern void cv_cnv_endian___int32_t( __int32_t *_ecnv_target_ );
extern void cv_cnv_endian___uint32_t( __uint32_t *_ecnv_target_ );
extern void cv_cnv_endian___int64_t( __int64_t *_ecnv_target_ );
extern void cv_cnv_endian___uint64_t( __uint64_t *_ecnv_target_ );
extern void cv_cnv_endian___quad_t( __quad_t *_ecnv_target_ );
extern void cv_cnv_endian___u_quad_t( __u_quad_t *_ecnv_target_ );
extern void cv_cnv_endian___dev_t( __dev_t *_ecnv_target_ );
extern void cv_cnv_endian___uid_t( __uid_t *_ecnv_target_ );
extern void cv_cnv_endian___gid_t( __gid_t *_ecnv_target_ );
extern void cv_cnv_endian___ino_t( __ino_t *_ecnv_target_ );
extern void cv_cnv_endian___ino64_t( __ino64_t *_ecnv_target_ );
extern void cv_cnv_endian___mode_t( __mode_t *_ecnv_target_ );
extern void cv_cnv_endian___nlink_t( __nlink_t *_ecnv_target_ );
extern void cv_cnv_endian___off_t( __off_t *_ecnv_target_ );
extern void cv_cnv_endian___off64_t( __off64_t *_ecnv_target_ );
extern void cv_cnv_endian___pid_t( __pid_t *_ecnv_target_ );
extern void cv_cnv_endian___fsid_t( __fsid_t *_ecnv_target_ );
extern void cv_cnv_endian___clock_t( __clock_t *_ecnv_target_ );
extern void cv_cnv_endian___rlim_t( __rlim_t *_ecnv_target_ );
extern void cv_cnv_endian___rlim64_t( __rlim64_t *_ecnv_target_ );
extern void cv_cnv_endian___id_t( __id_t *_ecnv_target_ );
extern void cv_cnv_endian___time_t( __time_t *_ecnv_target_ );
extern void cv_cnv_endian___useconds_t( __useconds_t *_ecnv_target_ );
extern void cv_cnv_endian___suseconds_t( __suseconds_t *_ecnv_target_ );
extern void cv_cnv_endian___daddr_t( __daddr_t *_ecnv_target_ );
extern void cv_cnv_endian___swblk_t( __swblk_t *_ecnv_target_ );
extern void cv_cnv_endian___key_t( __key_t *_ecnv_target_ );
extern void cv_cnv_endian___clockid_t( __clockid_t *_ecnv_target_ );
extern void cv_cnv_endian___timer_t( __timer_t *_ecnv_target_ );
extern void cv_cnv_endian___blksize_t( __blksize_t *_ecnv_target_ );
extern void cv_cnv_endian___blkcnt_t( __blkcnt_t *_ecnv_target_ );
extern void cv_cnv_endian___blkcnt64_t( __blkcnt64_t *_ecnv_target_ );
extern void cv_cnv_endian___fsblkcnt_t( __fsblkcnt_t *_ecnv_target_ );
extern void cv_cnv_endian___fsblkcnt64_t( __fsblkcnt64_t *_ecnv_target_ );
extern void cv_cnv_endian___fsfilcnt_t( __fsfilcnt_t *_ecnv_target_ );
extern void cv_cnv_endian___fsfilcnt64_t( __fsfilcnt64_t *_ecnv_target_ );
extern void cv_cnv_endian___ssize_t( __ssize_t *_ecnv_target_ );
extern void cv_cnv_endian___loff_t( __loff_t *_ecnv_target_ );
extern void cv_cnv_endian___qaddr_t( __qaddr_t *_ecnv_target_ );
extern void cv_cnv_endian___caddr_t( __caddr_t *_ecnv_target_ );
extern void cv_cnv_endian___intptr_t( __intptr_t *_ecnv_target_ );
extern void cv_cnv_endian___socklen_t( __socklen_t *_ecnv_target_ );
extern void cv_cnv_endian_FILE( FILE *_ecnv_target_ );
extern void cv_cnv_endian___FILE( __FILE *_ecnv_target_ );
extern void cv_cnv_endian___mbstate_t( __mbstate_t *_ecnv_target_ );
extern void cv_cnv_endian__G_fpos_t( _G_fpos_t *_ecnv_target_ );
extern void cv_cnv_endian__G_fpos64_t( _G_fpos64_t *_ecnv_target_ );
extern void cv_cnv_endian__G_int16_t( _G_int16_t *_ecnv_target_ );
extern void cv_cnv_endian__G_int32_t( _G_int32_t *_ecnv_target_ );
extern void cv_cnv_endian__G_uint16_t( _G_uint16_t *_ecnv_target_ );
extern void cv_cnv_endian__G_uint32_t( _G_uint32_t *_ecnv_target_ );
extern void cv_cnv_endian___gnuc_va_list( __gnuc_va_list *_ecnv_target_ );
extern void cv_cnv_endian__IO_lock_t( _IO_lock_t *_ecnv_target_ );
extern void cv_cnv_endian_struct__IO_marker( struct _IO_marker *_ecnv_target_ );
extern void cv_cnv_endian_enum___codecvt_result( enum __codecvt_result *_ecnv_target_ );
extern void cv_cnv_endian_struct__IO_FILE( struct _IO_FILE *_ecnv_target_ );
extern void cv_cnv_endian__IO_FILE( _IO_FILE *_ecnv_target_ );
extern void cv_cnv_endian_va_list( va_list *_ecnv_target_ );
extern void cv_cnv_endian_off_t( off_t *_ecnv_target_ );
extern void cv_cnv_endian_ssize_t( ssize_t *_ecnv_target_ );
extern void cv_cnv_endian_fpos_t( fpos_t *_ecnv_target_ );
extern void cv_cnv_endian_enum_e_fopen_mode( enum e_fopen_mode *_ecnv_target_ );
extern void cv_cnv_endian_t_fopen_mode( t_fopen_mode *_ecnv_target_ );
extern void cv_cnv_endian_datavalue( datavalue *_ecnv_target_ );
extern void cv_cnv_endian_SeqCfgSysCfgInfo( SeqCfgSysCfgInfo *_ecnv_target_ );
extern void cv_cnv_endian_SeqCfgSeqInfo( SeqCfgSeqInfo *_ecnv_target_ );
extern void cv_cnv_endian_SeqCfgCoreInfo( SeqCfgCoreInfo *_ecnv_target_ );
extern void cv_cnv_endian_SeqCfgRfTxInfo( SeqCfgRfTxInfo *_ecnv_target_ );
extern void cv_cnv_endian_SeqCfgRfGroupInfo( SeqCfgRfGroupInfo *_ecnv_target_ );
extern void cv_cnv_endian_SeqCfgInfo( SeqCfgInfo *_ecnv_target_ );
extern void cv_cnv_endian_struct_SeqType( struct SeqType *_ecnv_target_ );
extern void cv_cnv_endian_SeqType( SeqType *_ecnv_target_ );
extern void cv_cnv_endian_TYPDAB_PACKETS( TYPDAB_PACKETS *_ecnv_target_ );
extern void cv_cnv_endian_TYPACQ_PASS( TYPACQ_PASS *_ecnv_target_ );
extern void cv_cnv_endian_SeqData( SeqData *_ecnv_target_ );
extern void cv_cnv_endian_WF_HW_WAVEFORM_PTR( WF_HW_WAVEFORM_PTR *_ecnv_target_ );
extern void cv_cnv_endian_WF_HW_INSTR_PTR( WF_HW_INSTR_PTR *_ecnv_target_ );
extern void cv_cnv_endian_WF_PULSE_FORWARD_ADDR( WF_PULSE_FORWARD_ADDR *_ecnv_target_ );
extern void cv_cnv_endian_WF_INSTR_PTR( WF_INSTR_PTR *_ecnv_target_ );
extern void cv_cnv_endian_struct_INST_NODE( struct INST_NODE *_ecnv_target_ );
extern void cv_cnv_endian_WF_INSTR_HDR( WF_INSTR_HDR *_ecnv_target_ );
extern void cv_cnv_endian_CONST_EXT( CONST_EXT *_ecnv_target_ );
extern void cv_cnv_endian_HADAMARD_EXT( HADAMARD_EXT *_ecnv_target_ );
extern void cv_cnv_endian_RAMP_EXT( RAMP_EXT *_ecnv_target_ );
extern void cv_cnv_endian_SINC_EXT( SINC_EXT *_ecnv_target_ );
extern void cv_cnv_endian_SINUSOID_EXT( SINUSOID_EXT *_ecnv_target_ );
extern void cv_cnv_endian_WF_PULSE_EXT( WF_PULSE_EXT *_ecnv_target_ );
extern void cv_cnv_endian_WF_PULSE_TYPES( WF_PULSE_TYPES *_ecnv_target_ );
extern void cv_cnv_endian_WF_PGMTAG( WF_PGMTAG *_ecnv_target_ );
extern void cv_cnv_endian_WF_PGMREUSE( WF_PGMREUSE *_ecnv_target_ );
extern void cv_cnv_endian_struct_PULSE( struct PULSE *_ecnv_target_ );
extern void cv_cnv_endian_WF_PULSE( WF_PULSE *_ecnv_target_ );
extern void cv_cnv_endian_WF_PULSE_ADDR( WF_PULSE_ADDR *_ecnv_target_ );
extern void cv_cnv_endian_struct_INST_QUEUE_NODE( struct INST_QUEUE_NODE *_ecnv_target_ );
extern void cv_cnv_endian_WF_INSTR_QUEUE( WF_INSTR_QUEUE *_ecnv_target_ );
extern void cv_cnv_endian_SEQUENCE_ENTRIES( SEQUENCE_ENTRIES *_ecnv_target_ );
extern void cv_cnv_endian_struct_ENTRY_PT_NODE( struct ENTRY_PT_NODE *_ecnv_target_ );
extern void cv_cnv_endian_SEQUENCE_LIST( SEQUENCE_LIST *_ecnv_target_ );
extern void cv_cnv_endian_enum_rbw_update_type( enum rbw_update_type *_ecnv_target_ );
extern void cv_cnv_endian_RBW_UPDATE_TYPE( RBW_UPDATE_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_enum_filter_block_type( enum filter_block_type *_ecnv_target_ );
extern void cv_cnv_endian_FILTER_BLOCK_TYPE( FILTER_BLOCK_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_FILTER_INFO( FILTER_INFO *_ecnv_target_ );
extern void cv_cnv_endian_HOEC_CAL_INFO( HOEC_CAL_INFO *_ecnv_target_ );
extern void cv_cnv_endian_RDB_HOEC_BASES_TYPE( RDB_HOEC_BASES_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_PHYS_GRAD( PHYS_GRAD *_ecnv_target_ );
extern void cv_cnv_endian_t_xact( t_xact *_ecnv_target_ );
extern void cv_cnv_endian_t_yact( t_yact *_ecnv_target_ );
extern void cv_cnv_endian_t_zact( t_zact *_ecnv_target_ );
extern void cv_cnv_endian_ramp_t( ramp_t *_ecnv_target_ );
extern void cv_cnv_endian_LOG_GRAD( LOG_GRAD *_ecnv_target_ );
extern void cv_cnv_endian_OPT_GRAD_INPUT( OPT_GRAD_INPUT *_ecnv_target_ );
extern void cv_cnv_endian_OPT_GRAD_PARAMS( OPT_GRAD_PARAMS *_ecnv_target_ );
extern void cv_cnv_endian_clock_t( clock_t *_ecnv_target_ );
extern void cv_cnv_endian_time_t( time_t *_ecnv_target_ );
extern void cv_cnv_endian_clockid_t( clockid_t *_ecnv_target_ );
extern void cv_cnv_endian_timer_t( timer_t *_ecnv_target_ );
extern void cv_cnv_endian_struct_timespec( struct timespec *_ecnv_target_ );
extern void cv_cnv_endian_struct_tm( struct tm *_ecnv_target_ );
extern void cv_cnv_endian_struct_itimerspec( struct itimerspec *_ecnv_target_ );
extern void cv_cnv_endian_pid_t( pid_t *_ecnv_target_ );
extern void cv_cnv_endian_struct___locale_struct( struct __locale_struct *_ecnv_target_ );
extern void cv_cnv_endian___locale_t( __locale_t *_ecnv_target_ );
extern void cv_cnv_endian_locale_t( locale_t *_ecnv_target_ );
extern void cv_cnv_endian_GEtimespec( GEtimespec *_ecnv_target_ );
extern void cv_cnv_endian_dbkey_exam_type( dbkey_exam_type *_ecnv_target_ );
extern void cv_cnv_endian_dbkey_magic_type( dbkey_magic_type *_ecnv_target_ );
extern void cv_cnv_endian_dbkey_series_type( dbkey_series_type *_ecnv_target_ );
extern void cv_cnv_endian_dbkey_image_type( dbkey_image_type *_ecnv_target_ );
extern void cv_cnv_endian_DbKey( DbKey *_ecnv_target_ );
extern void cv_cnv_endian_OP_NMRID_TYPE( OP_NMRID_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_OP_HDR1_TYPE( OP_HDR1_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_struct__OP_HDR_TYPE( struct _OP_HDR_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_OP_HDR_TYPE( OP_HDR_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_struct__OP_RECN_READY_TYPE( struct _OP_RECN_READY_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_OP_RECN_READY_TYPE( OP_RECN_READY_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_struct__OP_RECN_READY_PACK_TYPE( struct _OP_RECN_READY_PACK_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_OP_RECN_READY_PACK_TYPE( OP_RECN_READY_PACK_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_OP_RECN_FOO_TYPE( OP_RECN_FOO_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_OP_RECN_FOO_PACK_TYPE( OP_RECN_FOO_PACK_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_struct__OP_RECN_START_TYPE( struct _OP_RECN_START_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_OP_RECN_START_TYPE( OP_RECN_START_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_struct__OP_RECN_START_PACK_TYPE( struct _OP_RECN_START_PACK_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_OP_RECN_START_PACK_TYPE( OP_RECN_START_PACK_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_OP_RECN_SCAN_STOPPED_TYPE( OP_RECN_SCAN_STOPPED_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_OP_RECN_SCAN_STOPPED_PACK_TYPE( OP_RECN_SCAN_STOPPED_PACK_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_OP_RECN_STOP_TYPE( OP_RECN_STOP_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_OP_RECN_STOP_PACK_TYPE( OP_RECN_STOP_PACK_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_OP_RECN_IM_ALLOC_TYPE( OP_RECN_IM_ALLOC_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_OP_RECN_IM_ALLOC_PACK_TYPE( OP_RECN_IM_ALLOC_PACK_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_OP_RECN_SCAN_STARTED_TYPE( OP_RECN_SCAN_STARTED_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_OP_RECN_SCAN_STARTED_PACK_TYPE( OP_RECN_SCAN_STARTED_PACK_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_OP_VIEWTABLE_UPDATE_TYPE( OP_VIEWTABLE_UPDATE_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_OP_VIEWTABLE_UPDATE_PACK_TYPE( OP_VIEWTABLE_UPDATE_PACK_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_MROR_ADDR_BLOCK( MROR_ADDR_BLOCK *_ecnv_target_ );
extern void cv_cnv_endian_MROR_ADDR_BLOCK_PKT( MROR_ADDR_BLOCK_PKT *_ecnv_target_ );
extern void cv_cnv_endian_MROR_RETRIEVAL_DONE_TYPE( MROR_RETRIEVAL_DONE_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_MROR_ADDR_BLOCK_PACK_TYPE( MROR_ADDR_BLOCK_PACK_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_SCAN_CALIB_INFO_TYPE( SCAN_CALIB_INFO_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_SCAN_CALIB_INFO_PACK_TYPE( SCAN_CALIB_INFO_PACK_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_struct__OP_RECN_SIZE_CHECK_TYPE( struct _OP_RECN_SIZE_CHECK_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_OP_RECN_SIZE_CHECK_TYPE( OP_RECN_SIZE_CHECK_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_struct__OP_RECN_SIZE_CHECK_PACK_TYPE( struct _OP_RECN_SIZE_CHECK_PACK_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_OP_RECN_SIZE_CHECK_PACK_TYPE( OP_RECN_SIZE_CHECK_PACK_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_EXAM_SCAN_DONE_TYPE( EXAM_SCAN_DONE_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_EXAM_SCAN_DONE_PACK_TYPE( EXAM_SCAN_DONE_PACK_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_struct__POSITION_DETECTION_DONE_TYPE( struct _POSITION_DETECTION_DONE_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_POSITION_DETECTION_DONE_TYPE( POSITION_DETECTION_DONE_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_struct__POSITION_DETECTION_DONE_PACK_TYPE( struct _POSITION_DETECTION_DONE_PACK_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_POSITION_DETECTION_DONE_PACK_TYPE( POSITION_DETECTION_DONE_PACK_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_struct__OP_CTT_UPDATE_TYPE( struct _OP_CTT_UPDATE_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_OP_CTT_UPDATE_TYPE( OP_CTT_UPDATE_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_struct__OP_CTT_UPDATE_PACK_TYPE( struct _OP_CTT_UPDATE_PACK_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_OP_CTT_UPDATE_PACK_TYPE( OP_CTT_UPDATE_PACK_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_enum_PSD_PSC_CONTROL( enum PSD_PSC_CONTROL *_ecnv_target_ );
extern void cv_cnv_endian_PSD_PSC_CONTROL_E( PSD_PSC_CONTROL_E *_ecnv_target_ );
extern void cv_cnv_endian_enum_GRADSHIM_SELECTION( enum GRADSHIM_SELECTION *_ecnv_target_ );
extern void cv_cnv_endian_GRADSHIM_SELECTION_E( GRADSHIM_SELECTION_E *_ecnv_target_ );
extern void cv_cnv_endian_enum_PRESSCFH_EXCITATION_TYPE( enum PRESSCFH_EXCITATION_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_PRESSCFH_EXCITATION_TYPE_E( PRESSCFH_EXCITATION_TYPE_E *_ecnv_target_ );
extern void cv_cnv_endian_struct_zy_index( struct zy_index *_ecnv_target_ );
extern void cv_cnv_endian_ZY_INDEX( ZY_INDEX *_ecnv_target_ );
extern void cv_cnv_endian_struct_zy_dist1( struct zy_dist1 *_ecnv_target_ );
extern void cv_cnv_endian_ZY_DIST1( ZY_DIST1 *_ecnv_target_ );
extern void cv_cnv_endian_struct__RDB_SLICE_INFO_ENTRY( struct _RDB_SLICE_INFO_ENTRY *_ecnv_target_ );
extern void cv_cnv_endian_RDB_SLICE_INFO_ENTRY( RDB_SLICE_INFO_ENTRY *_ecnv_target_ );
extern void cv_cnv_endian_EXTERN_FILENAME( EXTERN_FILENAME *_ecnv_target_ );
extern void cv_cnv_endian_EXTERN_FILENAME2( EXTERN_FILENAME2 *_ecnv_target_ );
extern void cv_cnv_endian_float_t( float_t *_ecnv_target_ );
extern void cv_cnv_endian_double_t( double_t *_ecnv_target_ );
extern void cv_cnv_endian__LIB_VERSION_TYPE( _LIB_VERSION_TYPE *_ecnv_target_ );
extern void cv_cnv_endian_struct_exception( struct exception *_ecnv_target_ );
extern void cv_cnv_endian_union_wait( union wait *_ecnv_target_ );
extern void cv_cnv_endian___WAIT_STATUS( __WAIT_STATUS *_ecnv_target_ );
extern void cv_cnv_endian_div_t( div_t *_ecnv_target_ );
extern void cv_cnv_endian_ldiv_t( ldiv_t *_ecnv_target_ );
extern void cv_cnv_endian_lldiv_t( lldiv_t *_ecnv_target_ );
extern void cv_cnv_endian_u_char( u_char *_ecnv_target_ );
extern void cv_cnv_endian_u_short( u_short *_ecnv_target_ );
extern void cv_cnv_endian_u_int( u_int *_ecnv_target_ );
extern void cv_cnv_endian_u_long( u_long *_ecnv_target_ );
extern void cv_cnv_endian_quad_t( quad_t *_ecnv_target_ );
extern void cv_cnv_endian_u_quad_t( u_quad_t *_ecnv_target_ );
extern void cv_cnv_endian_fsid_t( fsid_t *_ecnv_target_ );
extern void cv_cnv_endian_loff_t( loff_t *_ecnv_target_ );
extern void cv_cnv_endian_ino_t( ino_t *_ecnv_target_ );
extern void cv_cnv_endian_dev_t( dev_t *_ecnv_target_ );
extern void cv_cnv_endian_gid_t( gid_t *_ecnv_target_ );
extern void cv_cnv_endian_mode_t( mode_t *_ecnv_target_ );
extern void cv_cnv_endian_nlink_t( nlink_t *_ecnv_target_ );
extern void cv_cnv_endian_uid_t( uid_t *_ecnv_target_ );
extern void cv_cnv_endian_id_t( id_t *_ecnv_target_ );
extern void cv_cnv_endian_daddr_t( daddr_t *_ecnv_target_ );
extern void cv_cnv_endian_caddr_t( caddr_t *_ecnv_target_ );
extern void cv_cnv_endian_key_t( key_t *_ecnv_target_ );
extern void cv_cnv_endian_ulong( ulong *_ecnv_target_ );
extern void cv_cnv_endian_ushort( ushort *_ecnv_target_ );
extern void cv_cnv_endian_uint( uint *_ecnv_target_ );
extern void cv_cnv_endian_u_int8_t( u_int8_t *_ecnv_target_ );
extern void cv_cnv_endian_u_int16_t( u_int16_t *_ecnv_target_ );
extern void cv_cnv_endian_u_int32_t( u_int32_t *_ecnv_target_ );
extern void cv_cnv_endian_u_int64_t( u_int64_t *_ecnv_target_ );
extern void cv_cnv_endian_register_t( register_t *_ecnv_target_ );
extern void cv_cnv_endian___sig_atomic_t( __sig_atomic_t *_ecnv_target_ );
extern void cv_cnv_endian___sigset_t( __sigset_t *_ecnv_target_ );
extern void cv_cnv_endian_sigset_t( sigset_t *_ecnv_target_ );
extern void cv_cnv_endian_struct_timeval( struct timeval *_ecnv_target_ );
extern void cv_cnv_endian_suseconds_t( suseconds_t *_ecnv_target_ );
extern void cv_cnv_endian___fd_mask( __fd_mask *_ecnv_target_ );
extern void cv_cnv_endian_fd_set( fd_set *_ecnv_target_ );
extern void cv_cnv_endian_fd_mask( fd_mask *_ecnv_target_ );
extern void cv_cnv_endian_blksize_t( blksize_t *_ecnv_target_ );
extern void cv_cnv_endian_blkcnt_t( blkcnt_t *_ecnv_target_ );
extern void cv_cnv_endian_fsblkcnt_t( fsblkcnt_t *_ecnv_target_ );
extern void cv_cnv_endian_fsfilcnt_t( fsfilcnt_t *_ecnv_target_ );
extern void cv_cnv_endian_pthread_t( pthread_t *_ecnv_target_ );
extern void cv_cnv_endian_pthread_attr_t( pthread_attr_t *_ecnv_target_ );
extern void cv_cnv_endian_struct___pthread_internal_slist( struct __pthread_internal_slist *_ecnv_target_ );
extern void cv_cnv_endian___pthread_slist_t( __pthread_slist_t *_ecnv_target_ );
extern void cv_cnv_endian_struct___pthread_mutex_s( struct __pthread_mutex_s *_ecnv_target_ );
extern void cv_cnv_endian_pthread_mutex_t( pthread_mutex_t *_ecnv_target_ );
extern void cv_cnv_endian_pthread_mutexattr_t( pthread_mutexattr_t *_ecnv_target_ );
extern void cv_cnv_endian_pthread_cond_t( pthread_cond_t *_ecnv_target_ );
extern void cv_cnv_endian_pthread_condattr_t( pthread_condattr_t *_ecnv_target_ );
extern void cv_cnv_endian_pthread_key_t( pthread_key_t *_ecnv_target_ );
extern void cv_cnv_endian_pthread_once_t( pthread_once_t *_ecnv_target_ );
extern void cv_cnv_endian_pthread_rwlock_t( pthread_rwlock_t *_ecnv_target_ );
extern void cv_cnv_endian_pthread_rwlockattr_t( pthread_rwlockattr_t *_ecnv_target_ );
extern void cv_cnv_endian_pthread_spinlock_t( pthread_spinlock_t *_ecnv_target_ );
extern void cv_cnv_endian_pthread_barrier_t( pthread_barrier_t *_ecnv_target_ );
extern void cv_cnv_endian_pthread_barrierattr_t( pthread_barrierattr_t *_ecnv_target_ );
extern void cv_cnv_endian_struct_random_data( struct random_data *_ecnv_target_ );
extern void cv_cnv_endian_struct_drand48_data( struct drand48_data *_ecnv_target_ );
extern void cv_cnv_endian_enum_aptype_e( enum aptype_e *_ecnv_target_ );
extern void cv_cnv_endian_aptype_t( aptype_t *_ecnv_target_ );
extern void cv_cnv_endian_enum_dbLevel_e( enum dbLevel_e *_ecnv_target_ );
extern void cv_cnv_endian_dbLevel_t( dbLevel_t *_ecnv_target_ );
extern void cv_cnv_endian_COMPLEX( COMPLEX *_ecnv_target_ );
extern void cv_cnv_endian_PLAN_info( PLAN_info *_ecnv_target_ );
extern void cv_cnv_endian_FFT_setup( FFT_setup *_ecnv_target_ );
extern void cv_cnv_endian_lcomplex( lcomplex *_ecnv_target_ );
extern void cv_cnv_endian_dcomplex( dcomplex *_ecnv_target_ );
extern void cv_cnv_endian_struct_mss_result_s( struct mss_result_s *_ecnv_target_ );
extern void cv_cnv_endian_mss_result_t( mss_result_t *_ecnv_target_ );
extern void cv_cnv_endian_struct_mss_hw_s( struct mss_hw_s *_ecnv_target_ );
extern void cv_cnv_endian_mss_hw_t( mss_hw_t *_ecnv_target_ );
extern void cv_cnv_endian_struct_mss_wave_s( struct mss_wave_s *_ecnv_target_ );
extern void cv_cnv_endian_mss_wave_t( mss_wave_t *_ecnv_target_ );
extern void cv_cnv_endian_struct_mss_waveforms_s( struct mss_waveforms_s *_ecnv_target_ );
extern void cv_cnv_endian_mss_waveforms_t( mss_waveforms_t *_ecnv_target_ );
extern void cv_cnv_endian_struct_mss_geo_s( struct mss_geo_s *_ecnv_target_ );
extern void cv_cnv_endian_mss_geo_t( mss_geo_t *_ecnv_target_ );
extern void cv_cnv_endian_struct_mss_flags_s( struct mss_flags_s *_ecnv_target_ );
extern void cv_cnv_endian_mss_flags_t( mss_flags_t *_ecnv_target_ );
extern void cv_cnv_endian_struct_s_list( struct s_list *_ecnv_target_ );
extern void cv_cnv_endian_t_list( t_list *_ecnv_target_ );
extern void cv_cnv_endian_enum_logging_apptype( enum logging_apptype *_ecnv_target_ );
extern void cv_cnv_endian_logging_apptype_e( logging_apptype_e *_ecnv_target_ );
extern void cv_cnv_endian_enum_log_level( enum log_level *_ecnv_target_ );
extern void cv_cnv_endian_log_level_e( log_level_e *_ecnv_target_ );
extern void cv_cnv_endian_enum_trace_level( enum trace_level *_ecnv_target_ );
extern void cv_cnv_endian_trace_level_e( trace_level_e *_ecnv_target_ );
extern void cv_cnv_endian_enum_trace_file_name_style( enum trace_file_name_style *_ecnv_target_ );
extern void cv_cnv_endian_trace_file_name_style_e( trace_file_name_style_e *_ecnv_target_ );
extern void cv_cnv_endian_log_trace_return_e( log_trace_return_e *_ecnv_target_ );
extern void cv_cnv_endian_trace_module( trace_module *_ecnv_target_ );
extern void cv_cnv_endian_struct_maxslquanttps_option( struct maxslquanttps_option *_ecnv_target_ );
extern void cv_cnv_endian_MAXSLQUANTTPS_OPTION( MAXSLQUANTTPS_OPTION *_ecnv_target_ );
extern void cv_cnv_endian_enum_slicesort_acq_type( enum slicesort_acq_type *_ecnv_target_ );
extern void cv_cnv_endian_slicesort_acq_type_e( slicesort_acq_type_e *_ecnv_target_ );
extern void cv_cnv_endian_enum_jstdPositionErr_e( enum jstdPositionErr_e *_ecnv_target_ );
extern void cv_cnv_endian_jstdPositionErr_e( jstdPositionErr_e *_ecnv_target_ );
extern void cv_cnv_endian_struct_jstdConditions_s( struct jstdConditions_s *_ecnv_target_ );
extern void cv_cnv_endian_jstdConditions_t( jstdConditions_t *_ecnv_target_ );
extern void cv_cnv_endian_jstdReferencePosition_t( jstdReferencePosition_t *_ecnv_target_ );
extern void cv_cnv_endian_struct_jstdPositionResult_s( struct jstdPositionResult_s *_ecnv_target_ );
extern void cv_cnv_endian_jstdPositionResult_t( jstdPositionResult_t *_ecnv_target_ );
extern void cv_cnv_endian_struct_jstdResults_s( struct jstdResults_s *_ecnv_target_ );
extern void cv_cnv_endian_jstdResults_t( jstdResults_t *_ecnv_target_ );
extern void cv_cnv_endian_enum_scalerfpulses_b1_derate_type( enum scalerfpulses_b1_derate_type *_ecnv_target_ );
extern void cv_cnv_endian_scalerfpulses_b1_derate_type_e( scalerfpulses_b1_derate_type_e *_ecnv_target_ );
extern void cv_cnv_endian_enum_DABOUTHUBINDEX( enum DABOUTHUBINDEX *_ecnv_target_ );
extern void cv_cnv_endian_DABOUTHUBINDEX_E( DABOUTHUBINDEX_E *_ecnv_target_ );
extern void cv_cnv_endian_enum_DATA_FRAME_DESTINATION( enum DATA_FRAME_DESTINATION *_ecnv_target_ );
extern void cv_cnv_endian_DATA_FRAME_DESTINATION_E( DATA_FRAME_DESTINATION_E *_ecnv_target_ );
extern void cv_cnv_endian_enum_IMGOPT( enum IMGOPT *_ecnv_target_ );
extern void cv_cnv_endian_enum_psd_iopt_nums( enum psd_iopt_nums *_ecnv_target_ );
extern void cv_cnv_endian_psd_iopt_e( psd_iopt_e *_ecnv_target_ );
extern void cv_cnv_endian_struct_psdiopt_s( struct psdiopt_s *_ecnv_target_ );
extern void cv_cnv_endian_psdiopt_t( psdiopt_t *_ecnv_target_ );
extern void cv_cnv_endian_KS_DESCRIPTION( KS_DESCRIPTION *_ecnv_target_ );
extern void cv_cnv_endian_KS_WAVEFORM( KS_WAVEFORM *_ecnv_target_ );
extern void cv_cnv_endian_KS_IWAVE( KS_IWAVE *_ecnv_target_ );
extern void cv_cnv_endian_KS_MAT3x3( KS_MAT3x3 *_ecnv_target_ );
extern void cv_cnv_endian_KS_MAT4x4( KS_MAT4x4 *_ecnv_target_ );
extern void cv_cnv_endian_KS_PLOT_FILEFORMATS( KS_PLOT_FILEFORMATS *_ecnv_target_ );
extern void cv_cnv_endian_KS_PLOT_EXCITATION_MODE( KS_PLOT_EXCITATION_MODE *_ecnv_target_ );
extern void cv_cnv_endian_KS_PLOT_PASS_MODE( KS_PLOT_PASS_MODE *_ecnv_target_ );
extern void cv_cnv_endian_struct__seqloc_s( struct _seqloc_s *_ecnv_target_ );
extern void cv_cnv_endian_KS_SEQLOC( KS_SEQLOC *_ecnv_target_ );
extern void cv_cnv_endian_struct__wfinstance_s( struct _wfinstance_s *_ecnv_target_ );
extern void cv_cnv_endian_KS_WFINSTANCE( KS_WFINSTANCE *_ecnv_target_ );
extern void cv_cnv_endian_struct__base_s( struct _base_s *_ecnv_target_ );
extern void cv_cnv_endian_KS_BASE( KS_BASE *_ecnv_target_ );
extern void cv_cnv_endian_struct__wait_s( struct _wait_s *_ecnv_target_ );
extern void cv_cnv_endian_KS_WAIT( KS_WAIT *_ecnv_target_ );
extern void cv_cnv_endian_struct__isirot_s( struct _isirot_s *_ecnv_target_ );
extern void cv_cnv_endian_KS_ISIROT( KS_ISIROT *_ecnv_target_ );
extern void cv_cnv_endian_struct__trap_s( struct _trap_s *_ecnv_target_ );
extern void cv_cnv_endian_KS_TRAP( KS_TRAP *_ecnv_target_ );
extern void cv_cnv_endian_KS_WAVE( KS_WAVE *_ecnv_target_ );
extern void cv_cnv_endian_struct__acq_s( struct _acq_s *_ecnv_target_ );
extern void cv_cnv_endian_KS_READ( KS_READ *_ecnv_target_ );
extern void cv_cnv_endian_struct__rf_s( struct _rf_s *_ecnv_target_ );
extern void cv_cnv_endian_KS_RF( KS_RF *_ecnv_target_ );
extern void cv_cnv_endian_struct__gradrfctrl_s( struct _gradrfctrl_s *_ecnv_target_ );
extern void cv_cnv_endian_KS_GRADRFCTRL( KS_GRADRFCTRL *_ecnv_target_ );
extern void cv_cnv_endian_struct__seq_handle_s( struct _seq_handle_s *_ecnv_target_ );
extern void cv_cnv_endian_KS_SEQ_HANDLE( KS_SEQ_HANDLE *_ecnv_target_ );
extern void cv_cnv_endian_struct__seq_control_s( struct _seq_control_s *_ecnv_target_ );
extern void cv_cnv_endian_KS_SEQ_CONTROL( KS_SEQ_CONTROL *_ecnv_target_ );
extern void cv_cnv_endian_struct__seq_collection_s( struct _seq_collection_s *_ecnv_target_ );
extern void cv_cnv_endian_KS_SEQ_COLLECTION( KS_SEQ_COLLECTION *_ecnv_target_ );
extern void cv_cnv_endian_struct__sar_s( struct _sar_s *_ecnv_target_ );
extern void cv_cnv_endian_KS_SAR( KS_SAR *_ecnv_target_ );
extern void cv_cnv_endian_struct__KS_SLICE_PLAN( struct _KS_SLICE_PLAN *_ecnv_target_ );
extern void cv_cnv_endian_KS_SLICE_PLAN( KS_SLICE_PLAN *_ecnv_target_ );
extern void cv_cnv_endian_struct__sms_info_s( struct _sms_info_s *_ecnv_target_ );
extern void cv_cnv_endian_KS_SMS_INFO( KS_SMS_INFO *_ecnv_target_ );
extern void cv_cnv_endian_struct__selrf_s( struct _selrf_s *_ecnv_target_ );
extern void cv_cnv_endian_KS_SELRF( KS_SELRF *_ecnv_target_ );
extern void cv_cnv_endian_struct__readtrap_s( struct _readtrap_s *_ecnv_target_ );
extern void cv_cnv_endian_KS_READTRAP( KS_READTRAP *_ecnv_target_ );
extern void cv_cnv_endian_struct__readwave_s( struct _readwave_s *_ecnv_target_ );
extern void cv_cnv_endian_KS_READWAVE( KS_READWAVE *_ecnv_target_ );
extern void cv_cnv_endian_struct__phase_s( struct _phase_s *_ecnv_target_ );
extern void cv_cnv_endian_KS_PHASER( KS_PHASER *_ecnv_target_ );
extern void cv_cnv_endian_struct__3dphaseencodingplan_coord_s( struct _3dphaseencodingplan_coord_s *_ecnv_target_ );
extern void cv_cnv_endian_KS_PHASEENCODING_COORD( KS_PHASEENCODING_COORD *_ecnv_target_ );
extern void cv_cnv_endian_struct__3dphaseencodingplan_s( struct _3dphaseencodingplan_s *_ecnv_target_ );
extern void cv_cnv_endian_KS_PHASEENCODING_PLAN( KS_PHASEENCODING_PLAN *_ecnv_target_ );
extern void cv_cnv_endian_struct__epi_s( struct _epi_s *_ecnv_target_ );
extern void cv_cnv_endian_KS_EPI( KS_EPI *_ecnv_target_ );
extern void cv_cnv_endian_struct__dixon_dualreadtrap_s( struct _dixon_dualreadtrap_s *_ecnv_target_ );
extern void cv_cnv_endian_KS_DIXON_DUALREADTRAP( KS_DIXON_DUALREADTRAP *_ecnv_target_ );
extern void cv_cnv_endian_enum_ks_enum_trapparts( enum ks_enum_trapparts *_ecnv_target_ );
extern void cv_cnv_endian_enum_ks_enum_boarddef( enum ks_enum_boarddef *_ecnv_target_ );
extern void cv_cnv_endian_ks_enum_epiblipsign( ks_enum_epiblipsign *_ecnv_target_ );
extern void cv_cnv_endian_enum_ks_enum_diffusion( enum ks_enum_diffusion *_ecnv_target_ );
extern void cv_cnv_endian_enum_ks_enum_imsize( enum ks_enum_imsize *_ecnv_target_ );
extern void cv_cnv_endian_enum_ks_enum_datadestination( enum ks_enum_datadestination *_ecnv_target_ );
extern void cv_cnv_endian_enum_ks_enum_accelmenu( enum ks_enum_accelmenu *_ecnv_target_ );
extern void cv_cnv_endian_enum_ks_enum_rfrole( enum ks_enum_rfrole *_ecnv_target_ );
extern void cv_cnv_endian_enum_ks_enum_sincwin( enum ks_enum_sincwin *_ecnv_target_ );
extern void cv_cnv_endian_enum_ks_enum_wavebuf( enum ks_enum_wavebuf *_ecnv_target_ );
extern void cv_cnv_endian_enum_ks_enum_smstype( enum ks_enum_smstype *_ecnv_target_ );
extern void cv_cnv_endian_enum_ks_enum_sms_phase_mod( enum ks_enum_sms_phase_mod *_ecnv_target_ );
extern void cv_cnv_endian_enum_ks_enum_grad_scaling_policy( enum ks_enum_grad_scaling_policy *_ecnv_target_ );
extern void cv_cnv_endian_struct_KSGRE_SEQUENCE( struct KSGRE_SEQUENCE *_ecnv_target_ );
extern void cv_cnv_endian_KSGRE_SEQUENCE( KSGRE_SEQUENCE *_ecnv_target_ );

#ifdef __cplusplus
}
#endif /* __cplusplus */

