/*
 *  ksfse.exportstr.h
 *
 *  Do not edit this file. It is automatically generated by EPIC.
 *
 *  Date : Feb 28 2018
 *  Time : 11:06:49
 */

#ifndef h_ksfse_exportstr_h
#define h_ksfse_exportstr_h














_export _scan_info={(char *) scan_info,sizeof(scan_info),GE_STRUCT};


_export _mon_loc={(char *) &mon_loc,sizeof(mon_loc),GE_STRUCT};




_export _DATA_ACQ_ORDER_ENTRIES={(char *) &DATA_ACQ_ORDER_ENTRIES,sizeof(DATA_ACQ_ORDER_ENTRIES),GE_INT};
_export _data_acq_order={(char *) data_acq_order,sizeof(data_acq_order),GE_STRUCT};

_export 
























































_entry_point_table={(char *) entry_point_table,sizeof(entry_point_table),GE_STRUCT};

_export _psd_filt_spec={(char *) psd_filt_spec,sizeof(psd_filt_spec),GE_STRUCT};


_export _eg_sat_rot={(char *) eg_sat_rot,sizeof(eg_sat_rot),GE_STRUCT};







_export _psc_info={(char *) psc_info,sizeof(psc_info),GE_STRUCT};


_export _gir_info={(char *) gir_info,sizeof(gir_info),GE_STRUCT};


_export 








_hoec_cal_info={(char *) &hoec_cal_info,sizeof(hoec_cal_info),GE_STRUCT};


_export _rhdiffusion_grad_amp={(char *) rhdiffusion_grad_amp,sizeof(rhdiffusion_grad_amp),GE_STRUCT};


_export 





_rhhoec_bases={(char *) &rhhoec_bases,sizeof(rhhoec_bases),GE_STRUCT};


_export _pipscvol={(char *) &pipscvol,sizeof(pipscvol),GE_INT};




_export _ihtdeltab={(char *) &ihtdeltab,sizeof(ihtdeltab),GE_STRUCT};
_export _ihtrtab={(char *) &ihtrtab,sizeof(ihtrtab),GE_STRUCT};
_export _ihmaxtdelphase={(char *) &ihmaxtdelphase,sizeof(ihmaxtdelphase),GE_INT};
_export _ihtitab={(char *) &ihtitab,sizeof(ihtitab),GE_STRUCT};







_export _avminnecho={(char *) &avminnecho,sizeof(avminnecho),GE_INT};
_export _avmaxnecho={(char *) &avmaxnecho,sizeof(avmaxnecho),GE_INT};

_export _avminnshots={(char *) &avminnshots,sizeof(avminnshots),GE_INT};
_export _avmaxnshots={(char *) &avmaxnshots,sizeof(avmaxnshots),GE_INT};

_export _avminte={(char *) &avminte,sizeof(avminte),GE_INT};
_export _avmaxte={(char *) &avmaxte,sizeof(avmaxte),GE_INT};

_export _avminte2={(char *) &avminte2,sizeof(avminte2),GE_INT};
_export _avmaxte2={(char *) &avmaxte2,sizeof(avmaxte2),GE_INT};

_export _avmintissuet1={(char *) &avmintissuet1,sizeof(avmintissuet1),GE_INT};
_export _avmaxtissuet1={(char *) &avmaxtissuet1,sizeof(avmaxtissuet1),GE_INT};

_export _avminti={(char *) &avminti,sizeof(avminti),GE_INT};
_export _avmaxti={(char *) &avmaxti,sizeof(avmaxti),GE_INT};

_export _avminbspti={(char *) &avminbspti,sizeof(avminbspti),GE_INT};
_export _avmaxbspti={(char *) &avmaxbspti,sizeof(avmaxbspti),GE_INT};

_export _avmintrecovery={(char *) &avmintrecovery,sizeof(avmintrecovery),GE_INT};
_export _avmaxtrecovery={(char *) &avmaxtrecovery,sizeof(avmaxtrecovery),GE_INT};

_export _avmintlabel={(char *) &avmintlabel,sizeof(avmintlabel),GE_INT};
_export _avmaxtlabel={(char *) &avmaxtlabel,sizeof(avmaxtlabel),GE_INT};

_export _avmint2prepte={(char *) &avmint2prepte,sizeof(avmint2prepte),GE_INT};
_export _avmaxt2prepte={(char *) &avmaxt2prepte,sizeof(avmaxt2prepte),GE_INT};

_export _avminnspokes={(char *) &avminnspokes,sizeof(avminnspokes),GE_INT};
_export _avmaxnspokes={(char *) &avmaxnspokes,sizeof(avmaxnspokes),GE_INT};

_export _avminoversamplingfactor={(char *) &avminoversamplingfactor,sizeof(avminoversamplingfactor),GE_FLOAT};
_export _avmaxoversamplingfactor={(char *) &avmaxoversamplingfactor,sizeof(avmaxoversamplingfactor),GE_FLOAT};

_export _avmintr={(char *) &avmintr,sizeof(avmintr),GE_INT};
_export _avmaxtr={(char *) &avmaxtr,sizeof(avmaxtr),GE_INT};

_export _avminflip={(char *) &avminflip,sizeof(avminflip),GE_FLOAT};
_export _avmaxflip={(char *) &avmaxflip,sizeof(avmaxflip),GE_FLOAT};

_export _avminetl={(char *) &avminetl,sizeof(avminetl),GE_INT};
_export _avmaxetl={(char *) &avmaxetl,sizeof(avmaxetl),GE_INT};

_export _avminrbw={(char *) &avminrbw,sizeof(avminrbw),GE_FLOAT};
_export _avmaxrbw={(char *) &avmaxrbw,sizeof(avmaxrbw),GE_FLOAT};

_export _avminrbw2={(char *) &avminrbw2,sizeof(avminrbw2),GE_FLOAT};
_export _avmaxrbw2={(char *) &avmaxrbw2,sizeof(avmaxrbw2),GE_FLOAT};



_export _avminfov={(char *) &avminfov,sizeof(avminfov),GE_FLOAT};
_export _avmaxfov={(char *) &avmaxfov,sizeof(avmaxfov),GE_FLOAT};

_export _avminphasefov={(char *) &avminphasefov,sizeof(avminphasefov),GE_FLOAT};
_export _avmaxphasefov={(char *) &avmaxphasefov,sizeof(avmaxphasefov),GE_FLOAT};

_export _avminslthick={(char *) &avminslthick,sizeof(avminslthick),GE_FLOAT};
_export _avmaxslthick={(char *) &avmaxslthick,sizeof(avmaxslthick),GE_FLOAT};

_export _avminslspace={(char *) &avminslspace,sizeof(avminslspace),GE_FLOAT};
_export _avmaxslspace={(char *) &avmaxslspace,sizeof(avmaxslspace),GE_FLOAT};

_export _avminslquant={(char *) &avminslquant,sizeof(avminslquant),GE_INT};
_export _avmaxslquant={(char *) &avmaxslquant,sizeof(avmaxslquant),GE_INT};

_export _avmaxvquant={(char *) &avmaxvquant,sizeof(avmaxvquant),GE_INT};

_export _avmaxacqs={(char *) &avmaxacqs,sizeof(avmaxacqs),GE_INT};


_export _avmaxovl={(char *) &avmaxovl,sizeof(avmaxovl),GE_INT};




_export _avminxres={(char *) &avminxres,sizeof(avminxres),GE_INT};
_export _avmaxyres={(char *) &avmaxyres,sizeof(avmaxyres),GE_INT};

_export _avminyres={(char *) &avminyres,sizeof(avminyres),GE_INT};
_export _avmaxxres={(char *) &avmaxxres,sizeof(avmaxxres),GE_INT};

_export _avminnex={(char *) &avminnex,sizeof(avminnex),GE_FLOAT};
_export _avmaxnex={(char *) &avmaxnex,sizeof(avmaxnex),GE_FLOAT};

_export _avminslicecnt={(char *) &avminslicecnt,sizeof(avminslicecnt),GE_INT};
_export _avmaxslicecnt={(char *) &avmaxslicecnt,sizeof(avmaxslicecnt),GE_INT};



_export _avminphases={(char *) &avminphases,sizeof(avminphases),GE_INT};
_export _avmaxphases={(char *) &avmaxphases,sizeof(avmaxphases),GE_INT};

_export _avminaphases={(char *) &avminaphases,sizeof(avminaphases),GE_INT};
_export _avmaxaphases={(char *) &avmaxaphases,sizeof(avmaxaphases),GE_INT};

_export _avmintdel1={(char *) &avmintdel1,sizeof(avmintdel1),GE_INT};
_export _avmaxtdel1={(char *) &avmaxtdel1,sizeof(avmaxtdel1),GE_INT};
_export _pisystdel1={(char *) &pisystdel1,sizeof(pisystdel1),GE_INT};
_export _pidiatdel1={(char *) &pidiatdel1,sizeof(pidiatdel1),GE_INT};
_export _pitdel1={(char *) &pitdel1,sizeof(pitdel1),GE_INT};

_export _avminrttseq={(char *) &avminrttseq,sizeof(avminrttseq),GE_INT};


_export _avminnavaccwin={(char *) &avminnavaccwin,sizeof(avminnavaccwin),GE_FLOAT};
_export _avmaxnavaccwin={(char *) &avmaxnavaccwin,sizeof(avmaxnavaccwin),GE_FLOAT};
_export _avminnavautotrigtime={(char *) &avminnavautotrigtime,sizeof(avminnavautotrigtime),GE_INT};
_export _avmaxnavautotrigtime={(char *) &avmaxnavautotrigtime,sizeof(avmaxnavautotrigtime),GE_INT};
_export _avminnavpsctime={(char *) &avminnavpsctime,sizeof(avminnavpsctime),GE_INT};
_export _avmaxnavpsctime={(char *) &avmaxnavpsctime,sizeof(avmaxnavpsctime),GE_INT};
_export _avminnavrrmeastime={(char *) &avminnavrrmeastime,sizeof(avminnavrrmeastime),GE_INT};
_export _avmaxnavrrmeastime={(char *) &avmaxnavrrmeastime,sizeof(avmaxnavrrmeastime),GE_INT};
_export _avminnavmaxinterval={(char *) &avminnavmaxinterval,sizeof(avminnavmaxinterval),GE_INT};
_export _avmaxnavmaxinterval={(char *) &avmaxnavmaxinterval,sizeof(avmaxnavmaxinterval),GE_INT};


_export _pibreathholdnub={(char *) &pibreathholdnub,sizeof(pibreathholdnub),GE_INT};
_export _piautonavtracker={(char *) &piautonavtracker,sizeof(piautonavtracker),GE_INT};



_export _avminvenc={(char *) &avminvenc,sizeof(avminvenc),GE_FLOAT};
_export _avmaxvenc={(char *) &avmaxvenc,sizeof(avmaxvenc),GE_FLOAT};


_export _pimsdeaxnub={(char *) &pimsdeaxnub,sizeof(pimsdeaxnub),GE_INT};
_export _pivestnub={(char *) &pivestnub,sizeof(pivestnub),GE_INT};
_export _avminvest={(char *) &avminvest,sizeof(avminvest),GE_FLOAT};
_export _avmaxvest={(char *) &avmaxvest,sizeof(avmaxvest),GE_FLOAT};


_export _avmaxsldelay={(char *) &avmaxsldelay,sizeof(avmaxsldelay),GE_INT};

_export _avminfphases={(char *) &avminfphases,sizeof(avminfphases),GE_INT};
_export _avmaxfphases={(char *) &avmaxfphases,sizeof(avmaxfphases),GE_INT};


_export _avminvsphases={(char *) &avminvsphases,sizeof(avminvsphases),GE_INT};
_export _avmaxvsphases={(char *) &avmaxvsphases,sizeof(avmaxvsphases),GE_INT};
_export _avmindphases={(char *) &avmindphases,sizeof(avmindphases),GE_INT};


_export _avmintphases={(char *) &avmintphases,sizeof(avmintphases),GE_INT};
_export _avmaxtphases={(char *) &avmaxtphases,sizeof(avmaxtphases),GE_INT};
_export _avmintricksdel={(char *) &avmintricksdel,sizeof(avmintricksdel),GE_INT};
_export _avmaxtricksdel={(char *) &avmaxtricksdel,sizeof(avmaxtricksdel),GE_INT};



_export _avminbval={(char *) &avminbval,sizeof(avminbval),GE_INT};
_export _avmaxbval={(char *) &avmaxbval,sizeof(avmaxbval),GE_INT};

_export _avminrep_rest={(char *) &avminrep_rest,sizeof(avminrep_rest),GE_FLOAT};
_export _avmaxrep_rest={(char *) &avmaxrep_rest,sizeof(avmaxrep_rest),GE_FLOAT};

_export _avminrep_active={(char *) &avminrep_active,sizeof(avminrep_active),GE_FLOAT};
_export _avmaxrep_active={(char *) &avmaxrep_active,sizeof(avmaxrep_active),GE_FLOAT};

_export _avmin_dda={(char *) &avmin_dda,sizeof(avmin_dda),GE_FLOAT};
_export _avmax_dda={(char *) &avmax_dda,sizeof(avmax_dda),GE_FLOAT};

_export _avminnseg={(char *) &avminnseg,sizeof(avminnseg),GE_INT};
_export _avmaxnseg={(char *) &avmaxnseg,sizeof(avmaxnseg),GE_INT};

_export _avmintseq={(char *) &avmintseq,sizeof(avmintseq),GE_INT};
_export _avmaxtseq={(char *) &avmaxtseq,sizeof(avmaxtseq),GE_INT};



_export _avminslassetfac={(char *) &avminslassetfac,sizeof(avminslassetfac),GE_FLOAT};
_export _avmaxslassetfac={(char *) &avmaxslassetfac,sizeof(avmaxslassetfac),GE_FLOAT};
_export _avminphassetfac={(char *) &avminphassetfac,sizeof(avminphassetfac),GE_FLOAT};
_export _avmaxphassetfac={(char *) &avmaxphassetfac,sizeof(avmaxphassetfac),GE_FLOAT};


_export _avmintouchfreq={(char *) &avmintouchfreq,sizeof(avmintouchfreq),GE_INT};
_export _avmaxtouchfreq={(char *) &avmaxtouchfreq,sizeof(avmaxtouchfreq),GE_INT};
_export _avmintouchmegfreq={(char *) &avmintouchmegfreq,sizeof(avmintouchmegfreq),GE_INT};
_export _avmaxtouchmegfreq={(char *) &avmaxtouchmegfreq,sizeof(avmaxtouchmegfreq),GE_INT};
_export _avmintouchcyc={(char *) &avmintouchcyc,sizeof(avmintouchcyc),GE_INT};
_export _avmaxtouchcyc={(char *) &avmaxtouchcyc,sizeof(avmaxtouchcyc),GE_INT};
_export _avmintouchamp={(char *) &avmintouchamp,sizeof(avmintouchamp),GE_INT};
_export _avmaxtouchamp={(char *) &avmaxtouchamp,sizeof(avmaxtouchamp),GE_INT};
_export _avmintouchtphases={(char *) &avmintouchtphases,sizeof(avmintouchtphases),GE_INT};
_export _avmaxtouchtphases={(char *) &avmaxtouchtphases,sizeof(avmaxtouchtphases),GE_INT};

_export _avminnumbvals={(char *) &avminnumbvals,sizeof(avminnumbvals),GE_INT};
_export _avmaxnumbvals={(char *) &avmaxnumbvals,sizeof(avmaxnumbvals),GE_INT};

_export _avminbvalstab={(char *) &avminbvalstab,sizeof(avminbvalstab),GE_FLOAT};
_export _avmaxbvalstab={(char *) &avmaxbvalstab,sizeof(avmaxbvalstab),GE_FLOAT};

_export _avminnumsynbvals={(char *) &avminnumsynbvals,sizeof(avminnumsynbvals),GE_INT};
_export _avmaxnumsynbvals={(char *) &avmaxnumsynbvals,sizeof(avmaxnumsynbvals),GE_INT};

_export _avminsynbvalstab={(char *) &avminsynbvalstab,sizeof(avminsynbvalstab),GE_FLOAT};
_export _avmaxsynbvalstab={(char *) &avmaxsynbvalstab,sizeof(avmaxsynbvalstab),GE_FLOAT};

_export _avmindifnextab={(char *) &avmindifnextab,sizeof(avmindifnextab),GE_INT};
_export _avmaxdifnextab={(char *) &avmaxdifnextab,sizeof(avmaxdifnextab),GE_INT};

_export _avmindifnext2={(char *) &avmindifnext2,sizeof(avmindifnext2),GE_FLOAT};
_export _avmaxdifnext2={(char *) &avmaxdifnext2,sizeof(avmaxdifnext2),GE_FLOAT};


_export _avminallowedrescantime={(char *) &avminallowedrescantime,sizeof(avminallowedrescantime),GE_INT};
_export _avmaxallowedrescantime={(char *) &avmaxallowedrescantime,sizeof(avmaxallowedrescantime),GE_INT};
_export _pidefallowedrescantime={(char *) &pidefallowedrescantime,sizeof(pidefallowedrescantime),GE_INT};
_export _piallowedrescantimenub={(char *) &piallowedrescantimenub,sizeof(piallowedrescantimenub),GE_INT};






_export _piadvise={(char *) &piadvise,sizeof(piadvise),GE_INT};





















_export 

_piadvmin={(char *) &piadvmin,sizeof(piadvmin),GE_INT};
_export 

_piadvmax={(char *) &piadvmax,sizeof(piadvmax),GE_INT};


_export 
_piadvtime={(char *) &piadvtime,sizeof(piadvtime),GE_INT};


_export 

_piadvcard={(char *) &piadvcard,sizeof(piadvcard),GE_INT};



_export _pinsegnub={(char *) &pinsegnub,sizeof(pinsegnub),GE_INT};
_export _pinsegval2={(char *) &pinsegval2,sizeof(pinsegval2),GE_INT};
_export _pinsegval3={(char *) &pinsegval3,sizeof(pinsegval3),GE_INT};
_export _pinsegval4={(char *) &pinsegval4,sizeof(pinsegval4),GE_INT};
_export _pinsegval5={(char *) &pinsegval5,sizeof(pinsegval5),GE_INT};


_export _piframeratenub={(char *) &piframeratenub,sizeof(piframeratenub),GE_INT};
_export _piframerate={(char *) &piframerate,sizeof(piframerate),GE_FLOAT};

_export _piimages={(char *) &piimages,sizeof(piimages),GE_INT};



_export _pisatthick={(char *) &pisatthick,sizeof(pisatthick),GE_INT};
_export _pisatthickx={(char *) &pisatthickx,sizeof(pisatthickx),GE_INT};
_export _pisatthicky={(char *) &pisatthicky,sizeof(pisatthicky),GE_INT};
_export _pisatthickz={(char *) &pisatthickz,sizeof(pisatthickz),GE_INT};

_export _pisatnub={(char *) &pisatnub,sizeof(pisatnub),GE_INT};




_export _pimonitor={(char *) &pimonitor,sizeof(pimonitor),GE_INT};


_export _pimonfovnub={(char *) &pimonfovnub,sizeof(pimonfovnub),GE_INT};
_export _pimonfovval2={(char *) &pimonfovval2,sizeof(pimonfovval2),GE_FLOAT};
_export _pimonfovval3={(char *) &pimonfovval3,sizeof(pimonfovval3),GE_FLOAT};
_export _pimonfovval4={(char *) &pimonfovval4,sizeof(pimonfovval4),GE_FLOAT};
_export _pidfmonfov={(char *) &pidfmonfov,sizeof(pidfmonfov),GE_FLOAT};


_export _pimonthicknub={(char *) &pimonthicknub,sizeof(pimonthicknub),GE_INT};
_export _pimonthickval2={(char *) &pimonthickval2,sizeof(pimonthickval2),GE_FLOAT};
_export _pimonthickval3={(char *) &pimonthickval3,sizeof(pimonthickval3),GE_FLOAT};
_export _pimonthickval4={(char *) &pimonthickval4,sizeof(pimonthickval4),GE_FLOAT};
_export _pidfmonthick={(char *) &pidfmonthick,sizeof(pidfmonthick),GE_FLOAT};

_export _piccsat_obl={(char *) &piccsat_obl,sizeof(piccsat_obl),GE_INT};


_export _pichemsatopt={(char *) &pichemsatopt,sizeof(pichemsatopt),GE_INT};

_export _piccsatnub={(char *) &piccsatnub,sizeof(piccsatnub),GE_INT};

_export _pisupnub={(char *) &pisupnub,sizeof(pisupnub),GE_INT};

_export _piautopause={(char *) &piautopause,sizeof(piautopause),GE_INT};
_export _pislblank={(char *) &pislblank,sizeof(pislblank),GE_INT};

_export _pislthicklabel={(char *) &pislthicklabel,sizeof(pislthicklabel),GE_INT};
_export _pislthickstep={(char *) &pislthickstep,sizeof(pislthickstep),GE_FLOAT};


_export _pitseq={(char *) &pitseq,sizeof(pitseq),GE_INT};
_export _piait={(char *) &piait,sizeof(piait),GE_INT};
_export _pietr={(char *) &pietr,sizeof(pietr),GE_INT};


_export _picsifov={(char *) &picsifov,sizeof(picsifov),GE_INT};
_export _pirlcsi={(char *) &pirlcsi,sizeof(pirlcsi),GE_INT};
_export _piapcsi={(char *) &piapcsi,sizeof(piapcsi),GE_INT};
_export _pisicsi={(char *) &pisicsi,sizeof(pisicsi),GE_INT};
_export _piroigrx={(char *) &piroigrx,sizeof(piroigrx),GE_INT};


_export _pifilt4={(char *) &pifilt4,sizeof(pifilt4),GE_INT};
_export _pifilt5={(char *) &pifilt5,sizeof(pifilt5),GE_INT};
_export _pifilt6={(char *) &pifilt6,sizeof(pifilt6),GE_INT};
_export _pifilt7={(char *) &pifilt7,sizeof(pifilt7),GE_INT};

_export _pitfeextra={(char *) &pitfeextra,sizeof(pitfeextra),GE_INT};


_export _pitr={(char *) &pitr,sizeof(pitr),GE_INT};
_export _pichop={(char *) &pichop,sizeof(pichop),GE_INT};
_export _pitsp1={(char *) &pitsp1,sizeof(pitsp1),GE_INT};
_export _pitsp2={(char *) &pitsp2,sizeof(pitsp2),GE_INT};
_export _picalmode={(char *) &picalmode,sizeof(picalmode),GE_INT};
_export _pislquant={(char *) &pislquant,sizeof(pislquant),GE_INT};
_export _pinex={(char *) &pinex,sizeof(pinex),GE_INT};



_export _pimphscrn={(char *) &pimphscrn,sizeof(pimphscrn),GE_INT};



_export _pifphasenub={(char *) &pifphasenub,sizeof(pifphasenub),GE_INT};
_export _pifphaseval2={(char *) &pifphaseval2,sizeof(pifphaseval2),GE_INT};
_export _pifphaseval3={(char *) &pifphaseval3,sizeof(pifphaseval3),GE_INT};
_export _pifphaseval4={(char *) &pifphaseval4,sizeof(pifphaseval4),GE_INT};
_export _pifphaseval5={(char *) &pifphaseval5,sizeof(pifphaseval5),GE_INT};
_export _pifphaseval6={(char *) &pifphaseval6,sizeof(pifphaseval6),GE_INT};

_export _pisldelnub={(char *) &pisldelnub,sizeof(pisldelnub),GE_INT};
_export _pisldelval3={(char *) &pisldelval3,sizeof(pisldelval3),GE_INT};
_export _pisldelval4={(char *) &pisldelval4,sizeof(pisldelval4),GE_INT};
_export _pisldelval5={(char *) &pisldelval5,sizeof(pisldelval5),GE_INT};
_export _pisldelval6={(char *) &pisldelval6,sizeof(pisldelval6),GE_INT};

_export _piacqnub={(char *) &piacqnub,sizeof(piacqnub),GE_INT};


_export _pitphasenub={(char *) &pitphasenub,sizeof(pitphasenub),GE_INT};
_export _pitphaseval2={(char *) &pitphaseval2,sizeof(pitphaseval2),GE_INT};
_export _pitphaseval3={(char *) &pitphaseval3,sizeof(pitphaseval3),GE_INT};
_export _pitphaseval4={(char *) &pitphaseval4,sizeof(pitphaseval4),GE_INT};
_export _pitphaseval5={(char *) &pitphaseval5,sizeof(pitphaseval5),GE_INT};
_export _pitphaseval6={(char *) &pitphaseval6,sizeof(pitphaseval6),GE_INT};


_export _pivsphasenub={(char *) &pivsphasenub,sizeof(pivsphasenub),GE_INT};
_export _pivsphaseval2={(char *) &pivsphaseval2,sizeof(pivsphaseval2),GE_INT};
_export _pivsphaseval3={(char *) &pivsphaseval3,sizeof(pivsphaseval3),GE_INT};
_export _pivsphaseval4={(char *) &pivsphaseval4,sizeof(pivsphaseval4),GE_INT};
_export _pivsphaseval5={(char *) &pivsphaseval5,sizeof(pivsphaseval5),GE_INT};
_export _pivsphaseval6={(char *) &pivsphaseval6,sizeof(pivsphaseval6),GE_INT};

_export _pitricksdelnub={(char *) &pitricksdelnub,sizeof(pitricksdelnub),GE_INT};
_export _pitricksdelval3={(char *) &pitricksdelval3,sizeof(pitricksdelval3),GE_INT};
_export _pitricksdelval4={(char *) &pitricksdelval4,sizeof(pitricksdelval4),GE_INT};
_export _pitricksdelval5={(char *) &pitricksdelval5,sizeof(pitricksdelval5),GE_INT};
_export _pitricksdelval6={(char *) &pitricksdelval6,sizeof(pitricksdelval6),GE_INT};


_export _piuset={(char *) &piuset,sizeof(piuset),GE_INT};
_export _piuset2={(char *) &piuset2,sizeof(piuset2),GE_INT};


_export _pidualspinechonub={(char *) &pidualspinechonub,sizeof(pidualspinechonub),GE_INT};








_export _piechnub={(char *) &piechnub,sizeof(piechnub),GE_INT};
_export _piechdefval={(char *) &piechdefval,sizeof(piechdefval),GE_INT};
_export _piechval2={(char *) &piechval2,sizeof(piechval2),GE_INT};
_export _piechval3={(char *) &piechval3,sizeof(piechval3),GE_INT};
_export _piechval4={(char *) &piechval4,sizeof(piechval4),GE_INT};
_export _piechval5={(char *) &piechval5,sizeof(piechval5),GE_INT};
_export _piechval6={(char *) &piechval6,sizeof(piechval6),GE_INT};

_export _pishotnub={(char *) &pishotnub,sizeof(pishotnub),GE_INT};
_export _pishotval2={(char *) &pishotval2,sizeof(pishotval2),GE_INT};
_export _pishotval3={(char *) &pishotval3,sizeof(pishotval3),GE_INT};
_export _pishotval4={(char *) &pishotval4,sizeof(pishotval4),GE_INT};
_export _pishotval5={(char *) &pishotval5,sizeof(pishotval5),GE_INT};
_export _pishotval6={(char *) &pishotval6,sizeof(pishotval6),GE_INT};

_export _picineiprot={(char *) &picineiprot,sizeof(picineiprot),GE_INT};

_export _pitetype={(char *) &pitetype,sizeof(pitetype),GE_INT};
_export _pite1nub={(char *) &pite1nub,sizeof(pite1nub),GE_INT};
_export _pite1val2={(char *) &pite1val2,sizeof(pite1val2),GE_INT};
_export _pite1val3={(char *) &pite1val3,sizeof(pite1val3),GE_INT};
_export _pite1val4={(char *) &pite1val4,sizeof(pite1val4),GE_INT};
_export _pite1val5={(char *) &pite1val5,sizeof(pite1val5),GE_INT};
_export _pite1val6={(char *) &pite1val6,sizeof(pite1val6),GE_INT};

_export _pite2type={(char *) &pite2type,sizeof(pite2type),GE_INT};
_export _pite2nub={(char *) &pite2nub,sizeof(pite2nub),GE_INT};
_export _pite2val2={(char *) &pite2val2,sizeof(pite2val2),GE_INT};
_export _pite2val3={(char *) &pite2val3,sizeof(pite2val3),GE_INT};
_export _pite2val4={(char *) &pite2val4,sizeof(pite2val4),GE_INT};
_export _pite2val5={(char *) &pite2val5,sizeof(pite2val5),GE_INT};
_export _pite2val6={(char *) &pite2val6,sizeof(pite2val6),GE_INT};

_export _pitissuet1nub={(char *) &pitissuet1nub,sizeof(pitissuet1nub),GE_INT};
_export _pitissuet1defval={(char *) &pitissuet1defval,sizeof(pitissuet1defval),GE_INT};
_export _pitissuet1val2={(char *) &pitissuet1val2,sizeof(pitissuet1val2),GE_INT};
_export _pitissuet1val3={(char *) &pitissuet1val3,sizeof(pitissuet1val3),GE_INT};
_export _pitissuet1val4={(char *) &pitissuet1val4,sizeof(pitissuet1val4),GE_INT};
_export _pitissuet1val5={(char *) &pitissuet1val5,sizeof(pitissuet1val5),GE_INT};

_export _pititype={(char *) &pititype,sizeof(pititype),GE_INT};
_export _pitinub={(char *) &pitinub,sizeof(pitinub),GE_INT};
_export _pitidefval={(char *) &pitidefval,sizeof(pitidefval),GE_INT};
_export _pitival2={(char *) &pitival2,sizeof(pitival2),GE_INT};
_export _pitival3={(char *) &pitival3,sizeof(pitival3),GE_INT};
_export _pitival4={(char *) &pitival4,sizeof(pitival4),GE_INT};
_export _pitival5={(char *) &pitival5,sizeof(pitival5),GE_INT};
_export _pitival6={(char *) &pitival6,sizeof(pitival6),GE_INT};
_export _piautoti={(char *) &piautoti,sizeof(piautoti),GE_INT};


_export _pibsptinub={(char *) &pibsptinub,sizeof(pibsptinub),GE_INT};
_export _pibsptidefval={(char *) &pibsptidefval,sizeof(pibsptidefval),GE_INT};
_export _pibsptival2={(char *) &pibsptival2,sizeof(pibsptival2),GE_INT};
_export _pibsptival3={(char *) &pibsptival3,sizeof(pibsptival3),GE_INT};
_export _pibsptival4={(char *) &pibsptival4,sizeof(pibsptival4),GE_INT};
_export _pibsptival5={(char *) &pibsptival5,sizeof(pibsptival5),GE_INT};
_export _pibsptival6={(char *) &pibsptival6,sizeof(pibsptival6),GE_INT};
_export _piautobspti={(char *) &piautobspti,sizeof(piautobspti),GE_INT};

_export _pitrecoverynub={(char *) &pitrecoverynub,sizeof(pitrecoverynub),GE_INT};
_export _pitrecoverystep={(char *) &pitrecoverystep,sizeof(pitrecoverystep),GE_INT};
_export _pitrecoverylabel={(char *) pitrecoverylabel,sizeof(pitrecoverylabel),GE_STRUCT};
_export _pitrecoverydefval={(char *) &pitrecoverydefval,sizeof(pitrecoverydefval),GE_INT};
_export _pitrecoveryval2={(char *) &pitrecoveryval2,sizeof(pitrecoveryval2),GE_INT};
_export _pitrecoveryval3={(char *) &pitrecoveryval3,sizeof(pitrecoveryval3),GE_INT};
_export _pitrecoveryval4={(char *) &pitrecoveryval4,sizeof(pitrecoveryval4),GE_INT};
_export _pitrecoveryval5={(char *) &pitrecoveryval5,sizeof(pitrecoveryval5),GE_INT};
_export _pitrecoveryval6={(char *) &pitrecoveryval6,sizeof(pitrecoveryval6),GE_INT};

_export _pitlabelnub={(char *) &pitlabelnub,sizeof(pitlabelnub),GE_INT};
_export _pitlabelstep={(char *) &pitlabelstep,sizeof(pitlabelstep),GE_INT};
_export _pitlabeldefval={(char *) &pitlabeldefval,sizeof(pitlabeldefval),GE_INT};
_export _pitlabelval2={(char *) &pitlabelval2,sizeof(pitlabelval2),GE_INT};
_export _pitlabelval3={(char *) &pitlabelval3,sizeof(pitlabelval3),GE_INT};
_export _pitlabelval4={(char *) &pitlabelval4,sizeof(pitlabelval4),GE_INT};

_export _pit2preptenub={(char *) &pit2preptenub,sizeof(pit2preptenub),GE_INT};
_export _pit2preptedefval={(char *) &pit2preptedefval,sizeof(pit2preptedefval),GE_INT};
_export _pit2prepteval2={(char *) &pit2prepteval2,sizeof(pit2prepteval2),GE_INT};
_export _pit2prepteval3={(char *) &pit2prepteval3,sizeof(pit2prepteval3),GE_INT};
_export _pit2prepteval4={(char *) &pit2prepteval4,sizeof(pit2prepteval4),GE_INT};
_export _pit2prepteval5={(char *) &pit2prepteval5,sizeof(pit2prepteval5),GE_INT};
_export _pit2prepteval6={(char *) &pit2prepteval6,sizeof(pit2prepteval6),GE_INT};

_export _pinspokesnub={(char *) &pinspokesnub,sizeof(pinspokesnub),GE_INT};
_export _pinspokesstep={(char *) &pinspokesstep,sizeof(pinspokesstep),GE_INT};
_export _pinspokesdefval={(char *) &pinspokesdefval,sizeof(pinspokesdefval),GE_INT};
_export _pinspokesval2={(char *) &pinspokesval2,sizeof(pinspokesval2),GE_INT};
_export _pinspokesval3={(char *) &pinspokesval3,sizeof(pinspokesval3),GE_INT};
_export _pinspokesval4={(char *) &pinspokesval4,sizeof(pinspokesval4),GE_INT};
_export _pinspokesval5={(char *) &pinspokesval5,sizeof(pinspokesval5),GE_INT};
_export _pinspokesval6={(char *) &pinspokesval6,sizeof(pinspokesval6),GE_INT};

_export _pioversamplingfactornub={(char *) &pioversamplingfactornub,sizeof(pioversamplingfactornub),GE_INT};
_export _pioversamplingfactordefval={(char *) &pioversamplingfactordefval,sizeof(pioversamplingfactordefval),GE_FLOAT};
_export _pioversamplingfactorval2={(char *) &pioversamplingfactorval2,sizeof(pioversamplingfactorval2),GE_FLOAT};
_export _pioversamplingfactorval3={(char *) &pioversamplingfactorval3,sizeof(pioversamplingfactorval3),GE_FLOAT};
_export _pioversamplingfactorval4={(char *) &pioversamplingfactorval4,sizeof(pioversamplingfactorval4),GE_FLOAT};
_export _pioversamplingfactorval5={(char *) &pioversamplingfactorval5,sizeof(pioversamplingfactorval5),GE_FLOAT};
_export _pioversamplingfactorval6={(char *) &pioversamplingfactorval6,sizeof(pioversamplingfactorval6),GE_FLOAT};

_export _piacsnub={(char *) &piacsnub,sizeof(piacsnub),GE_INT};
_export _piacsdefval={(char *) &piacsdefval,sizeof(piacsdefval),GE_INT};
_export _piacsval2={(char *) &piacsval2,sizeof(piacsval2),GE_INT};
_export _piacsval3={(char *) &piacsval3,sizeof(piacsval3),GE_INT};
_export _piacsval4={(char *) &piacsval4,sizeof(piacsval4),GE_INT};
_export _piacsval5={(char *) &piacsval5,sizeof(piacsval5),GE_INT};
_export _piacsval6={(char *) &piacsval6,sizeof(piacsval6),GE_INT};

_export _piharmonizenub={(char *) &piharmonizenub,sizeof(piharmonizenub),GE_INT};

_export _pieffbladewidthnub={(char *) &pieffbladewidthnub,sizeof(pieffbladewidthnub),GE_INT};
_export _pieffbladewidthdefval={(char *) &pieffbladewidthdefval,sizeof(pieffbladewidthdefval),GE_INT};

_export _pisilentmr={(char *) &pisilentmr,sizeof(pisilentmr),GE_INT};
_export _pinslices={(char *) &pinslices,sizeof(pinslices),GE_INT};

_export _pitrnub={(char *) &pitrnub,sizeof(pitrnub),GE_INT};
_export _pitrval2={(char *) &pitrval2,sizeof(pitrval2),GE_INT};
_export _pitrval3={(char *) &pitrval3,sizeof(pitrval3),GE_INT};
_export _pitrval4={(char *) &pitrval4,sizeof(pitrval4),GE_INT};
_export _pitrval5={(char *) &pitrval5,sizeof(pitrval5),GE_INT};
_export _pitrval6={(char *) &pitrval6,sizeof(pitrval6),GE_INT};
_export _piinrangetrmin={(char *) &piinrangetrmin,sizeof(piinrangetrmin),GE_INT};
_export _piinrangetrmax={(char *) &piinrangetrmax,sizeof(piinrangetrmax),GE_INT};
_export _piautotrmode={(char *) &piautotrmode,sizeof(piautotrmode),GE_INT};

_export _pifanub={(char *) &pifanub,sizeof(pifanub),GE_INT};
_export _pifaval2={(char *) &pifaval2,sizeof(pifaval2),GE_INT};
_export _pifaval3={(char *) &pifaval3,sizeof(pifaval3),GE_INT};
_export _pifaval4={(char *) &pifaval4,sizeof(pifaval4),GE_INT};
_export _pifaval5={(char *) &pifaval5,sizeof(pifaval5),GE_INT};
_export _pifaval6={(char *) &pifaval6,sizeof(pifaval6),GE_INT};
_export _piautofa={(char *) &piautofa,sizeof(piautofa),GE_INT};
_export _pifamode={(char *) &pifamode,sizeof(pifamode),GE_INT};

_export _pietlnub={(char *) &pietlnub,sizeof(pietlnub),GE_INT};
_export _pietlval2={(char *) &pietlval2,sizeof(pietlval2),GE_INT};
_export _pietlval3={(char *) &pietlval3,sizeof(pietlval3),GE_INT};
_export _pietlval4={(char *) &pietlval4,sizeof(pietlval4),GE_INT};
_export _pietlval5={(char *) &pietlval5,sizeof(pietlval5),GE_INT};
_export _pietlval6={(char *) &pietlval6,sizeof(pietlval6),GE_INT};
_export _piautoetl={(char *) &piautoetl,sizeof(piautoetl),GE_INT};









_export _piassetoverride={(char *) &piassetoverride,sizeof(piassetoverride),GE_INT};











_export _piphassetnub={(char *) &piphassetnub,sizeof(piphassetnub),GE_INT};
_export _piphassetval1={(char *) &piphassetval1,sizeof(piphassetval1),GE_FLOAT};
_export _piphassetval2={(char *) &piphassetval2,sizeof(piphassetval2),GE_FLOAT};
_export _piphassetval3={(char *) &piphassetval3,sizeof(piphassetval3),GE_FLOAT};
_export _piphassetval4={(char *) &piphassetval4,sizeof(piphassetval4),GE_FLOAT};
_export _pidefphasset={(char *) &pidefphasset,sizeof(pidefphasset),GE_FLOAT};

_export _pislassetnub={(char *) &pislassetnub,sizeof(pislassetnub),GE_INT};
_export _pislassetval1={(char *) &pislassetval1,sizeof(pislassetval1),GE_FLOAT};
_export _pislassetval2={(char *) &pislassetval2,sizeof(pislassetval2),GE_FLOAT};
_export _pislassetval3={(char *) &pislassetval3,sizeof(pislassetval3),GE_FLOAT};
_export _pislassetval4={(char *) &pislassetval4,sizeof(pislassetval4),GE_FLOAT};
_export _pidefslasset={(char *) &pidefslasset,sizeof(pidefslasset),GE_FLOAT};


_export _picalmodenub={(char *) &picalmodenub,sizeof(picalmodenub),GE_INT};
_export _pidefcaldelay={(char *) &pidefcaldelay,sizeof(pidefcaldelay),GE_INT};

_export _pipure={(char *) &pipure,sizeof(pipure),GE_INT};

_export _pirbwpage={(char *) &pirbwpage,sizeof(pirbwpage),GE_INT};
_export _pidefrbw={(char *) &pidefrbw,sizeof(pidefrbw),GE_FLOAT};
_export _pircbnub={(char *) &pircbnub,sizeof(pircbnub),GE_INT};
_export _pircbval2={(char *) &pircbval2,sizeof(pircbval2),GE_FLOAT};
_export _pircbval3={(char *) &pircbval3,sizeof(pircbval3),GE_FLOAT};
_export _pircbval4={(char *) &pircbval4,sizeof(pircbval4),GE_FLOAT};
_export _pircbval5={(char *) &pircbval5,sizeof(pircbval5),GE_FLOAT};
_export _pircbval6={(char *) &pircbval6,sizeof(pircbval6),GE_FLOAT};

_export _pircb2nub={(char *) &pircb2nub,sizeof(pircb2nub),GE_INT};
_export _pircb2val2={(char *) &pircb2val2,sizeof(pircb2val2),GE_FLOAT};
_export _pircb2val3={(char *) &pircb2val3,sizeof(pircb2val3),GE_FLOAT};
_export _pircb2val4={(char *) &pircb2val4,sizeof(pircb2val4),GE_FLOAT};
_export _pircb2val5={(char *) &pircb2val5,sizeof(pircb2val5),GE_FLOAT};
_export _pircb2val6={(char *) &pircb2val6,sizeof(pircb2val6),GE_FLOAT};


_export _piflosup={(char *) &piflosup,sizeof(piflosup),GE_INT};

_export _piflanub={(char *) &piflanub,sizeof(piflanub),GE_INT};
_export _pivelnub={(char *) &pivelnub,sizeof(pivelnub),GE_INT};
_export _piprojnub={(char *) &piprojnub,sizeof(piprojnub),GE_INT};
_export _piaddinub={(char *) &piaddinub,sizeof(piaddinub),GE_INT};
_export _piflrcnub={(char *) &piflrcnub,sizeof(piflrcnub),GE_INT};

_export _pirampnub={(char *) &pirampnub,sizeof(pirampnub),GE_INT};
_export _pideframp={(char *) &pideframp,sizeof(pideframp),GE_INT};



_export _piscran={(char *) &piscran,sizeof(piscran),GE_INT};

_export _pifovnub={(char *) &pifovnub,sizeof(pifovnub),GE_INT};
_export _pifovval2={(char *) &pifovval2,sizeof(pifovval2),GE_FLOAT};
_export _pifovval3={(char *) &pifovval3,sizeof(pifovval3),GE_FLOAT};
_export _pifovval4={(char *) &pifovval4,sizeof(pifovval4),GE_FLOAT};
_export _pifovval5={(char *) &pifovval5,sizeof(pifovval5),GE_FLOAT};
_export _pifovval6={(char *) &pifovval6,sizeof(pifovval6),GE_FLOAT};

_export _piphasfovnub={(char *) &piphasfovnub,sizeof(piphasfovnub),GE_INT};

_export _pifreqfovnub={(char *) &pifreqfovnub,sizeof(pifreqfovnub),GE_INT};

_export _piphasfovnub2={(char *) &piphasfovnub2,sizeof(piphasfovnub2),GE_INT};

_export _piphasfovval1={(char *) &piphasfovval1,sizeof(piphasfovval1),GE_FLOAT};
_export _piphasfovval2={(char *) &piphasfovval2,sizeof(piphasfovval2),GE_FLOAT};
_export _piphasfovval3={(char *) &piphasfovval3,sizeof(piphasfovval3),GE_FLOAT};
_export _piphasfovval4={(char *) &piphasfovval4,sizeof(piphasfovval4),GE_FLOAT};
_export _piphasfovval5={(char *) &piphasfovval5,sizeof(piphasfovval5),GE_FLOAT};
_export _piphasfovval6={(char *) &piphasfovval6,sizeof(piphasfovval6),GE_FLOAT};

_export _pistnub={(char *) &pistnub,sizeof(pistnub),GE_INT};
_export _pistval2={(char *) &pistval2,sizeof(pistval2),GE_FLOAT};
_export _pistval3={(char *) &pistval3,sizeof(pistval3),GE_FLOAT};
_export _pistval4={(char *) &pistval4,sizeof(pistval4),GE_FLOAT};
_export _pistval5={(char *) &pistval5,sizeof(pistval5),GE_FLOAT};
_export _pistval6={(char *) &pistval6,sizeof(pistval6),GE_FLOAT};

_export _piisnub={(char *) &piisnub,sizeof(piisnub),GE_INT};
_export _piisil={(char *) &piisil,sizeof(piisil),GE_INT};
_export _piisval2={(char *) &piisval2,sizeof(piisval2),GE_FLOAT};
_export _piisval3={(char *) &piisval3,sizeof(piisval3),GE_FLOAT};
_export _piisval4={(char *) &piisval4,sizeof(piisval4),GE_FLOAT};
_export _piisval5={(char *) &piisval5,sizeof(piisval5),GE_FLOAT};
_export _piisval6={(char *) &piisval6,sizeof(piisval6),GE_FLOAT};


_export _pipctovl={(char *) &pipctovl,sizeof(pipctovl),GE_INT};
_export _pidefovl={(char *) &pidefovl,sizeof(pidefovl),GE_INT};
_export _piovlnub={(char *) &piovlnub,sizeof(piovlnub),GE_INT};

_export _pilocnub={(char *) &pilocnub,sizeof(pilocnub),GE_INT};
_export _pilocval2={(char *) &pilocval2,sizeof(pilocval2),GE_INT};
_export _pilocval3={(char *) &pilocval3,sizeof(pilocval3),GE_INT};
_export _pilocval4={(char *) &pilocval4,sizeof(pilocval4),GE_INT};
_export _pilocval5={(char *) &pilocval5,sizeof(pilocval5),GE_INT};
_export _pilocval6={(char *) &pilocval6,sizeof(pilocval6),GE_INT};


_export _pislqnub={(char *) &pislqnub,sizeof(pislqnub),GE_INT};
_export _pislqval2={(char *) &pislqval2,sizeof(pislqval2),GE_INT};
_export _pislqval3={(char *) &pislqval3,sizeof(pislqval3),GE_INT};
_export _pislqval4={(char *) &pislqval4,sizeof(pislqval4),GE_INT};
_export _pidefslq={(char *) &pidefslq,sizeof(pidefslq),GE_INT};
_export _pislqval5={(char *) &pislqval5,sizeof(pislqval5),GE_INT};


_export _piactim={(char *) &piactim,sizeof(piactim),GE_INT};


_export _piamnub={(char *) &piamnub,sizeof(piamnub),GE_INT};
_export _piamval1={(char *) piamval1,sizeof(piamval1),GE_STRUCT};
_export _piamval2={(char *) piamval2,sizeof(piamval2),GE_STRUCT};
_export _piamval3={(char *) piamval3,sizeof(piamval3),GE_STRUCT};
_export _piamval4={(char *) piamval4,sizeof(piamval4),GE_STRUCT};
_export _piamval5={(char *) piamval5,sizeof(piamval5),GE_STRUCT};
_export _piamval6={(char *) piamval6,sizeof(piamval6),GE_STRUCT};

_export _pitresnub={(char *) &pitresnub,sizeof(pitresnub),GE_INT};
_export _pitres2nub={(char *) &pitres2nub,sizeof(pitres2nub),GE_INT};

_export _pixresnub={(char *) &pixresnub,sizeof(pixresnub),GE_INT};
_export _pixresval2={(char *) &pixresval2,sizeof(pixresval2),GE_INT};
_export _pixresval3={(char *) &pixresval3,sizeof(pixresval3),GE_INT};
_export _pixresval4={(char *) &pixresval4,sizeof(pixresval4),GE_INT};
_export _pixresval5={(char *) &pixresval5,sizeof(pixresval5),GE_INT};
_export _pixresval6={(char *) &pixresval6,sizeof(pixresval6),GE_INT};

_export _piyresnub={(char *) &piyresnub,sizeof(piyresnub),GE_INT};
_export _piyresval2={(char *) &piyresval2,sizeof(piyresval2),GE_INT};
_export _piyresval3={(char *) &piyresval3,sizeof(piyresval3),GE_INT};
_export _piyresval4={(char *) &piyresval4,sizeof(piyresval4),GE_INT};
_export _piyresval5={(char *) &piyresval5,sizeof(piyresval5),GE_INT};
_export _piyresval6={(char *) &piyresval6,sizeof(piyresval6),GE_INT};

_export _pinexnub={(char *) &pinexnub,sizeof(pinexnub),GE_INT};
_export _pinexval2={(char *) &pinexval2,sizeof(pinexval2),GE_FLOAT};
_export _pinexval3={(char *) &pinexval3,sizeof(pinexval3),GE_FLOAT};
_export _pinexval4={(char *) &pinexval4,sizeof(pinexval4),GE_FLOAT};
_export _pinexval5={(char *) &pinexval5,sizeof(pinexval5),GE_FLOAT};
_export _pinexval6={(char *) &pinexval6,sizeof(pinexval6),GE_FLOAT};


_export _pisctim={(char *) &pisctim,sizeof(pisctim),GE_INT};
_export _pisctim1={(char *) &pisctim1,sizeof(pisctim1),GE_FLOAT};
_export _pisctim2={(char *) &pisctim2,sizeof(pisctim2),GE_FLOAT};
_export _pisctim3={(char *) &pisctim3,sizeof(pisctim3),GE_FLOAT};
_export _pisctim4={(char *) &pisctim4,sizeof(pisctim4),GE_FLOAT};
_export _pisctim5={(char *) &pisctim5,sizeof(pisctim5),GE_FLOAT};
_export _pisctim6={(char *) &pisctim6,sizeof(pisctim6),GE_FLOAT};

_export _pipautype={(char *) &pipautype,sizeof(pipautype),GE_INT};
_export _pipaunub={(char *) &pipaunub,sizeof(pipaunub),GE_INT};
_export _pipauval2={(char *) &pipauval2,sizeof(pipauval2),GE_INT};
_export _pipauval3={(char *) &pipauval3,sizeof(pipauval3),GE_INT};
_export _pipauval4={(char *) &pipauval4,sizeof(pipauval4),GE_INT};
_export _pipauval5={(char *) &pipauval5,sizeof(pipauval5),GE_INT};
_export _pipauval6={(char *) &pipauval6,sizeof(pipauval6),GE_INT};

_export _piswapfc={(char *) &piswapfc,sizeof(piswapfc),GE_INT};
_export _pipscoptnub={(char *) &pipscoptnub,sizeof(pipscoptnub),GE_INT};

_export _pidoshim={(char *) &pidoshim,sizeof(pidoshim),GE_INT};
_export _pidotg={(char *) &pidotg,sizeof(pidotg),GE_INT};
_export _xtg_disabled={(char *) &xtg_disabled,sizeof(xtg_disabled),GE_INT};

_export _pipscshimtgnub={(char *) &pipscshimtgnub,sizeof(pipscshimtgnub),GE_INT};

_export _pidyntgnub={(char *) &pidyntgnub,sizeof(pidyntgnub),GE_INT};


_export _pifsefcnub={(char *) &pifsefcnub,sizeof(pifsefcnub),GE_INT};
_export _pideffcaxis={(char *) &pideffcaxis,sizeof(pideffcaxis),GE_INT};


_export _pidltime={(char *) &pidltime,sizeof(pidltime),GE_INT};



_export _pihrepnub={(char *) &pihrepnub,sizeof(pihrepnub),GE_INT};
_export _pihrepval2={(char *) &pihrepval2,sizeof(pihrepval2),GE_INT};
_export _pihrepval3={(char *) &pihrepval3,sizeof(pihrepval3),GE_INT};
_export _pihrepval4={(char *) &pihrepval4,sizeof(pihrepval4),GE_INT};
_export _pihrepval5={(char *) &pihrepval5,sizeof(pihrepval5),GE_INT};
_export _pihrepval6={(char *) &pihrepval6,sizeof(pihrepval6),GE_INT};


_export _pidefarr={(char *) &pidefarr,sizeof(pidefarr),GE_INT};


_export _pifcinenub={(char *) &pifcinenub,sizeof(pifcinenub),GE_INT};
_export _pifcinedefval={(char *) &pifcinedefval,sizeof(pifcinedefval),GE_INT};
_export _pifcineval2={(char *) &pifcineval2,sizeof(pifcineval2),GE_INT};
_export _pifcineval3={(char *) &pifcineval3,sizeof(pifcineval3),GE_INT};
_export _pifcineval4={(char *) &pifcineval4,sizeof(pifcineval4),GE_INT};

_export _piaphasenub={(char *) &piaphasenub,sizeof(piaphasenub),GE_INT};
_export _piaphasdefval={(char *) &piaphasdefval,sizeof(piaphasdefval),GE_INT};
_export _piaphaseval2={(char *) &piaphaseval2,sizeof(piaphaseval2),GE_INT};
_export _piaphaseval3={(char *) &piaphaseval3,sizeof(piaphaseval3),GE_INT};
_export _piaphaseval4={(char *) &piaphaseval4,sizeof(piaphaseval4),GE_INT};


_export _piautophasenub={(char *) &piautophasenub,sizeof(piautophasenub),GE_INT};


_export _pitagging={(char *) &pitagging,sizeof(pitagging),GE_INT};
_export _pitagspcdefval={(char *) &pitagspcdefval,sizeof(pitagspcdefval),GE_INT};
_export _pitagspcval2={(char *) &pitagspcval2,sizeof(pitagspcval2),GE_INT};
_export _pitagspcval3={(char *) &pitagspcval3,sizeof(pitagspcval3),GE_INT};
_export _pitagspcval4={(char *) &pitagspcval4,sizeof(pitagspcval4),GE_INT};


_export _pitaganglenub={(char *) &pitaganglenub,sizeof(pitaganglenub),GE_INT};
_export _pitagangledefval={(char *) &pitagangledefval,sizeof(pitagangledefval),GE_FLOAT};
_export _pitagangleval2={(char *) &pitagangleval2,sizeof(pitagangleval2),GE_FLOAT};
_export _pitagangleval3={(char *) &pitagangleval3,sizeof(pitagangleval3),GE_FLOAT};
_export _pitagangleval4={(char *) &pitagangleval4,sizeof(pitagangleval4),GE_FLOAT};
_export _pitagangleval5={(char *) &pitagangleval5,sizeof(pitagangleval5),GE_FLOAT};
_export _pitagangleval6={(char *) &pitagangleval6,sizeof(pitagangleval6),GE_FLOAT};


_export _pitdel1nub={(char *) &pitdel1nub,sizeof(pitdel1nub),GE_INT};
_export _pitdel1type={(char *) &pitdel1type,sizeof(pitdel1type),GE_INT};
_export _pitrigwinnub={(char *) &pitrigwinnub,sizeof(pitrigwinnub),GE_INT};
_export _pitseqnub={(char *) &pitseqnub,sizeof(pitseqnub),GE_INT};
_export _pitseqtype={(char *) &pitseqtype,sizeof(pitseqtype),GE_INT};
_export _piphasenub={(char *) &piphasenub,sizeof(piphasenub),GE_INT};
_export _piphslnub={(char *) &piphslnub,sizeof(piphslnub),GE_INT};
_export _piviewseg={(char *) &piviewseg,sizeof(piviewseg),GE_INT};
_export _pivpsdef={(char *) &pivpsdef,sizeof(pivpsdef),GE_INT};

_export _pitetr={(char *) &pitetr,sizeof(pitetr),GE_INT};

_export _piautovoice={(char *) &piautovoice,sizeof(piautovoice),GE_INT};

_export _pirtrigwinnub={(char *) &pirtrigwinnub,sizeof(pirtrigwinnub),GE_INT};
_export _pirtwindefval={(char *) &pirtwindefval,sizeof(pirtwindefval),GE_INT};
_export _pirtwinval2={(char *) &pirtwinval2,sizeof(pirtwinval2),GE_INT};
_export _pirtwinval3={(char *) &pirtwinval3,sizeof(pirtwinval3),GE_INT};
_export _pirtwinval4={(char *) &pirtwinval4,sizeof(pirtwinval4),GE_INT};
_export _pirtwinval5={(char *) &pirtwinval5,sizeof(pirtwinval5),GE_INT};
_export _pirtwinval6={(char *) &pirtwinval6,sizeof(pirtwinval6),GE_INT};

_export _pirtseqnub={(char *) &pirtseqnub,sizeof(pirtseqnub),GE_INT};
_export _pirttseq={(char *) &pirttseq,sizeof(pirttseq),GE_INT};
_export _pirtait={(char *) &pirtait,sizeof(pirtait),GE_INT};
_export _pirtetr={(char *) &pirtetr,sizeof(pirtetr),GE_INT};

_export _pirtrepnub={(char *) &pirtrepnub,sizeof(pirtrepnub),GE_INT};
_export _pirtrepval2={(char *) &pirtrepval2,sizeof(pirtrepval2),GE_INT};
_export _pirtrepval3={(char *) &pirtrepval3,sizeof(pirtrepval3),GE_INT};
_export _pirtrepval4={(char *) &pirtrepval4,sizeof(pirtrepval4),GE_INT};
_export _pirtrepval5={(char *) &pirtrepval5,sizeof(pirtrepval5),GE_INT};
_export _pirtrepval6={(char *) &pirtrepval6,sizeof(pirtrepval6),GE_INT};
_export _pidefrtrep={(char *) &pidefrtrep,sizeof(pidefrtrep),GE_INT};

_export _pirtpointnub={(char *) &pirtpointnub,sizeof(pirtpointnub),GE_INT};
_export _pirtpointval2={(char *) &pirtpointval2,sizeof(pirtpointval2),GE_INT};
_export _pirtpointval3={(char *) &pirtpointval3,sizeof(pirtpointval3),GE_INT};
_export _pirtpointval4={(char *) &pirtpointval4,sizeof(pirtpointval4),GE_INT};
_export _pirtpointval5={(char *) &pirtpointval5,sizeof(pirtpointval5),GE_INT};
_export _pirtpointval6={(char *) &pirtpointval6,sizeof(pirtpointval6),GE_INT};

_export _pirtratenub={(char *) &pirtratenub,sizeof(pirtratenub),GE_INT};

_export _pinavsltracknub={(char *) &pinavsltracknub,sizeof(pinavsltracknub),GE_INT};
_export _pidefnavsltrack={(char *) &pidefnavsltrack,sizeof(pidefnavsltrack),GE_INT};

_export _pinavautoaccwinnub={(char *) &pinavautoaccwinnub,sizeof(pinavautoaccwinnub),GE_INT};
_export _pidefnavautoaccwin={(char *) &pidefnavautoaccwin,sizeof(pidefnavautoaccwin),GE_INT};

_export _pinavrrmeasnub={(char *) &pinavrrmeasnub,sizeof(pinavrrmeasnub),GE_INT};
_export _pidefnavrrmeas={(char *) &pidefnavrrmeas,sizeof(pidefnavrrmeas),GE_INT};

_export _pinavaccwinnub={(char *) &pinavaccwinnub,sizeof(pinavaccwinnub),GE_INT};
_export _pinavaccwinval2={(char *) &pinavaccwinval2,sizeof(pinavaccwinval2),GE_INT};
_export _pinavaccwinval3={(char *) &pinavaccwinval3,sizeof(pinavaccwinval3),GE_INT};
_export _pinavaccwinval4={(char *) &pinavaccwinval4,sizeof(pinavaccwinval4),GE_INT};
_export _pidefnavaccwin={(char *) &pidefnavaccwin,sizeof(pidefnavaccwin),GE_INT};

_export _pinavautotrigtimenub={(char *) &pinavautotrigtimenub,sizeof(pinavautotrigtimenub),GE_INT};
_export _pinavautotrigtimeval2={(char *) &pinavautotrigtimeval2,sizeof(pinavautotrigtimeval2),GE_INT};
_export _pinavautotrigtimeval3={(char *) &pinavautotrigtimeval3,sizeof(pinavautotrigtimeval3),GE_INT};
_export _pinavautotrigtimeval4={(char *) &pinavautotrigtimeval4,sizeof(pinavautotrigtimeval4),GE_INT};
_export _pidefnavautotrigtime={(char *) &pidefnavautotrigtime,sizeof(pidefnavautotrigtime),GE_INT};

_export _pinavpsctimenub={(char *) &pinavpsctimenub,sizeof(pinavpsctimenub),GE_INT};
_export _pinavpsctimeval2={(char *) &pinavpsctimeval2,sizeof(pinavpsctimeval2),GE_INT};
_export _pinavpsctimeval3={(char *) &pinavpsctimeval3,sizeof(pinavpsctimeval3),GE_INT};
_export _pinavpsctimeval4={(char *) &pinavpsctimeval4,sizeof(pinavpsctimeval4),GE_INT};
_export _pidefnavpsctime={(char *) &pidefnavpsctime,sizeof(pidefnavpsctime),GE_INT};

_export _pinavrrmeastimenub={(char *) &pinavrrmeastimenub,sizeof(pinavrrmeastimenub),GE_INT};
_export _pinavrrmeastimeval2={(char *) &pinavrrmeastimeval2,sizeof(pinavrrmeastimeval2),GE_INT};
_export _pinavrrmeastimeval3={(char *) &pinavrrmeastimeval3,sizeof(pinavrrmeastimeval3),GE_INT};
_export _pinavrrmeastimeval4={(char *) &pinavrrmeastimeval4,sizeof(pinavrrmeastimeval4),GE_INT};
_export _pidefnavrrmeastime={(char *) &pidefnavrrmeastime,sizeof(pidefnavrrmeastime),GE_INT};

_export _pinavmaxintervalnub={(char *) &pinavmaxintervalnub,sizeof(pinavmaxintervalnub),GE_INT};
_export _pinavmaxintervalval2={(char *) &pinavmaxintervalval2,sizeof(pinavmaxintervalval2),GE_INT};
_export _pinavmaxintervalval3={(char *) &pinavmaxintervalval3,sizeof(pinavmaxintervalval3),GE_INT};
_export _pinavmaxintervalval4={(char *) &pinavmaxintervalval4,sizeof(pinavmaxintervalval4),GE_INT};
_export _pidefnavmaxinterval={(char *) &pidefnavmaxinterval,sizeof(pidefnavmaxinterval),GE_INT};

_export _pinavtypenub={(char *) &pinavtypenub,sizeof(pinavtypenub),GE_INT};
_export _pidefnavtype={(char *) &pidefnavtype,sizeof(pidefnavtype),GE_INT};

_export _pinavpscpausenub={(char *) &pinavpscpausenub,sizeof(pinavpscpausenub),GE_INT};
_export _pidefnavpscpause={(char *) &pidefnavpscpause,sizeof(pidefnavpscpause),GE_INT};

_export _pinavsigenhancenub={(char *) &pinavsigenhancenub,sizeof(pinavsigenhancenub),GE_INT};
_export _pidefnavsigenhance={(char *) &pidefnavsigenhance,sizeof(pidefnavsigenhance),GE_INT};

_export _pinavmaxrr={(char *) &pinavmaxrr,sizeof(pinavmaxrr),GE_FLOAT};
_export _pinavrrmeasmaxsl={(char *) &pinavrrmeasmaxsl,sizeof(pinavrrmeasmaxsl),GE_INT};
_export _pinavrrmeasrtrep={(char *) &pinavrrmeasrtrep,sizeof(pinavrrmeasrtrep),GE_INT};
_export _pinavrradjust={(char *) &pinavrradjust,sizeof(pinavrradjust),GE_INT};


_export _pivascop={(char *) &pivascop,sizeof(pivascop),GE_INT};


_export _pizmult={(char *) &pizmult,sizeof(pizmult),GE_INT};
_export _pimultigroup={(char *) &pimultigroup,sizeof(pimultigroup),GE_INT};
_export _pimultislab={(char *) &pimultislab,sizeof(pimultislab),GE_INT};


_export _pidefproj={(char *) &pidefproj,sizeof(pidefproj),GE_INT};
_export _pidefflax={(char *) &pidefflax,sizeof(pidefflax),GE_INT};
_export _pidefaddimg={(char *) &pidefaddimg,sizeof(pidefaddimg),GE_INT};
_export _pidefflrc={(char *) &pidefflrc,sizeof(pidefflrc),GE_INT};

_export _pigradcoil={(char *) &pigradcoil,sizeof(pigradcoil),GE_INT};

_export _dfscale={(char *) &dfscale,sizeof(dfscale),GE_FLOAT};


_export _pipscdef={(char *) &pipscdef,sizeof(pipscdef),GE_INT};





_export _pidifpage={(char *) &pidifpage,sizeof(pidifpage),GE_INT};

_export _pidifaxnub={(char *) &pidifaxnub,sizeof(pidifaxnub),GE_INT};
_export _pidifaxval1={(char *) pidifaxval1,sizeof(pidifaxval1),GE_STRUCT};
_export _pidifaxval2={(char *) pidifaxval2,sizeof(pidifaxval2),GE_STRUCT};
_export _pidifaxval3={(char *) pidifaxval3,sizeof(pidifaxval3),GE_STRUCT};
_export _pidifaxval4={(char *) pidifaxval4,sizeof(pidifaxval4),GE_STRUCT};
_export _pidifaxval5={(char *) pidifaxval5,sizeof(pidifaxval5),GE_STRUCT};
_export _pidifaxval6={(char *) pidifaxval6,sizeof(pidifaxval6),GE_STRUCT};

_export _pidiffproctype={(char *) &pidiffproctype,sizeof(pidiffproctype),GE_INT};
_export _pidifnumdirsnub={(char *) &pidifnumdirsnub,sizeof(pidifnumdirsnub),GE_INT};
_export _pidifnumdirsdefval={(char *) &pidifnumdirsdefval,sizeof(pidifnumdirsdefval),GE_INT};
_export _pidifnumdirsval2={(char *) &pidifnumdirsval2,sizeof(pidifnumdirsval2),GE_INT};
_export _pidifnumdirsval3={(char *) &pidifnumdirsval3,sizeof(pidifnumdirsval3),GE_INT};
_export _pidifnumdirsval4={(char *) &pidifnumdirsval4,sizeof(pidifnumdirsval4),GE_INT};
_export _pidifnumt2nub={(char *) &pidifnumt2nub,sizeof(pidifnumt2nub),GE_INT};
_export _pidifnumt2defval={(char *) &pidifnumt2defval,sizeof(pidifnumt2defval),GE_INT};
_export _pidifnumt2val2={(char *) &pidifnumt2val2,sizeof(pidifnumt2val2),GE_INT};
_export _pidifnumt2val3={(char *) &pidifnumt2val3,sizeof(pidifnumt2val3),GE_INT};
_export _pidifnumt2val4={(char *) &pidifnumt2val4,sizeof(pidifnumt2val4),GE_INT};

_export _pidefbval={(char *) &pidefbval,sizeof(pidefbval),GE_INT};
_export _pibvnub={(char *) &pibvnub,sizeof(pibvnub),GE_INT};
_export _pibval2={(char *) &pibval2,sizeof(pibval2),GE_INT};
_export _pibval3={(char *) &pibval3,sizeof(pibval3),GE_INT};
_export _pibval4={(char *) &pibval4,sizeof(pibval4),GE_INT};

_export _pidifrecnub={(char *) &pidifrecnub,sizeof(pidifrecnub),GE_INT};

_export _pidifrecval1={(char *) pidifrecval1,sizeof(pidifrecval1),GE_STRUCT};
_export _pidfirecval2={(char *) pidfirecval2,sizeof(pidfirecval2),GE_STRUCT};
_export _pidfirecval3={(char *) pidfirecval3,sizeof(pidfirecval3),GE_STRUCT};
_export _pidfirecval4={(char *) pidfirecval4,sizeof(pidfirecval4),GE_STRUCT};
_export _pidfirecval5={(char *) pidfirecval5,sizeof(pidfirecval5),GE_STRUCT};

_export _pimintedifnub={(char *) &pimintedifnub,sizeof(pimintedifnub),GE_INT};
_export _pimintedifdef={(char *) &pimintedifdef,sizeof(pimintedifdef),GE_INT};

_export _piseparatesynbnub={(char *) &piseparatesynbnub,sizeof(piseparatesynbnub),GE_INT};


_export _pinumbnub={(char *) &pinumbnub,sizeof(pinumbnub),GE_INT};
_export _pinumbval2={(char *) &pinumbval2,sizeof(pinumbval2),GE_INT};
_export _pinumbval3={(char *) &pinumbval3,sizeof(pinumbval3),GE_INT};
_export _pinumbval4={(char *) &pinumbval4,sizeof(pinumbval4),GE_INT};
_export _pinumbval5={(char *) &pinumbval5,sizeof(pinumbval5),GE_INT};
_export _pinumbval6={(char *) &pinumbval6,sizeof(pinumbval6),GE_INT};


_export _pinumsynbnub={(char *) &pinumsynbnub,sizeof(pinumsynbnub),GE_INT};
_export _pinumsynbval2={(char *) &pinumsynbval2,sizeof(pinumsynbval2),GE_INT};
_export _pinumsynbval3={(char *) &pinumsynbval3,sizeof(pinumsynbval3),GE_INT};
_export _pinumsynbval4={(char *) &pinumsynbval4,sizeof(pinumsynbval4),GE_INT};
_export _pinumsynbval5={(char *) &pinumsynbval5,sizeof(pinumsynbval5),GE_INT};
_export _pinumsynbval6={(char *) &pinumsynbval6,sizeof(pinumsynbval6),GE_INT};


_export _pidifnext2nub={(char *) &pidifnext2nub,sizeof(pidifnext2nub),GE_INT};
_export _pidifnext2val2={(char *) &pidifnext2val2,sizeof(pidifnext2val2),GE_FLOAT};
_export _pidifnext2val3={(char *) &pidifnext2val3,sizeof(pidifnext2val3),GE_FLOAT};
_export _pidifnext2val4={(char *) &pidifnext2val4,sizeof(pidifnext2val4),GE_FLOAT};
_export _pidifnext2val5={(char *) &pidifnext2val5,sizeof(pidifnext2val5),GE_FLOAT};
_export _pidifnext2val6={(char *) &pidifnext2val6,sizeof(pidifnext2val6),GE_FLOAT};

_export _pibvalstab={(char *) &pibvalstab,sizeof(pibvalstab),GE_INT};
_export _pisynbvalstab={(char *) &pisynbvalstab,sizeof(pisynbvalstab),GE_INT};
_export _pidifnextab={(char *) &pidifnextab,sizeof(pidifnextab),GE_INT};
_export _pidifavgnex={(char *) &pidifavgnex,sizeof(pidifavgnex),GE_FLOAT};


_export _pimultistation={(char *) &pimultistation,sizeof(pimultistation),GE_INT};
_export _piautostep={(char *) &piautostep,sizeof(piautostep),GE_INT};
_export _pisioverlap={(char *) &pisioverlap,sizeof(pisioverlap),GE_INT};


_export _pisetup={(char *) &pisetup,sizeof(pisetup),GE_INT};


_export _picasar={(char *) &picasar,sizeof(picasar),GE_FLOAT};
_export _pipsar={(char *) &pipsar,sizeof(pipsar),GE_FLOAT};
_export _piasar={(char *) &piasar,sizeof(piasar),GE_FLOAT};
_export _pihsar={(char *) &pihsar,sizeof(pihsar),GE_FLOAT};
_export _pitsar={(char *) &pitsar,sizeof(pitsar),GE_FLOAT};
_export _piesar={(char *) &piesar,sizeof(piesar),GE_FLOAT};


_export _pib1rms={(char *) &pib1rms,sizeof(pib1rms),GE_FLOAT};



_export _piimgoptval2={(char *) &piimgoptval2,sizeof(piimgoptval2),GE_INT};
_export _piimgoptval3={(char *) &piimgoptval3,sizeof(piimgoptval3),GE_INT};
_export _piimgoptval4={(char *) &piimgoptval4,sizeof(piimgoptval4),GE_INT};

_export _pidixproc={(char *) &pidixproc,sizeof(pidixproc),GE_INT};


_export _piadvt2map={(char *) &piadvt2map,sizeof(piadvt2map),GE_INT};



_export _pitablemaxspeed={(char *) &pitablemaxspeed,sizeof(pitablemaxspeed),GE_INT};
_export _pitablemaxaccel={(char *) &pitablemaxaccel,sizeof(pitablemaxaccel),GE_INT};
_export _pitablemaxdecel={(char *) &pitablemaxdecel,sizeof(pitablemaxdecel),GE_INT};




_export _pitouch={(char *) &pitouch,sizeof(pitouch),GE_INT};
_export _pitouchfreq={(char *) &pitouchfreq,sizeof(pitouchfreq),GE_INT};
_export _pitouchamp={(char *) &pitouchamp,sizeof(pitouchamp),GE_INT};
_export _pitouchcyc={(char *) &pitouchcyc,sizeof(pitouchcyc),GE_INT};
_export _pitouchtphases={(char *) &pitouchtphases,sizeof(pitouchtphases),GE_INT};

_export _pitouchfreqnub={(char *) &pitouchfreqnub,sizeof(pitouchfreqnub),GE_INT};
_export _pitouchfreqval2={(char *) &pitouchfreqval2,sizeof(pitouchfreqval2),GE_INT};
_export _pitouchfreqval3={(char *) &pitouchfreqval3,sizeof(pitouchfreqval3),GE_INT};
_export _pitouchfreqval4={(char *) &pitouchfreqval4,sizeof(pitouchfreqval4),GE_INT};
_export _pideftouchfreq={(char *) &pideftouchfreq,sizeof(pideftouchfreq),GE_INT};

_export _pitouchmegfreqnub={(char *) &pitouchmegfreqnub,sizeof(pitouchmegfreqnub),GE_INT};
_export _pitouchmegfreqval2={(char *) &pitouchmegfreqval2,sizeof(pitouchmegfreqval2),GE_INT};
_export _pitouchmegfreqval3={(char *) &pitouchmegfreqval3,sizeof(pitouchmegfreqval3),GE_INT};
_export _pitouchmegfreqval4={(char *) &pitouchmegfreqval4,sizeof(pitouchmegfreqval4),GE_INT};
_export _pideftouchmegfreq={(char *) &pideftouchmegfreq,sizeof(pideftouchmegfreq),GE_INT};

_export _pitouchampnub={(char *) &pitouchampnub,sizeof(pitouchampnub),GE_INT};
_export _pitouchampval2={(char *) &pitouchampval2,sizeof(pitouchampval2),GE_INT};
_export _pitouchampval3={(char *) &pitouchampval3,sizeof(pitouchampval3),GE_INT};
_export _pitouchampval4={(char *) &pitouchampval4,sizeof(pitouchampval4),GE_INT};
_export _pideftouchamp={(char *) &pideftouchamp,sizeof(pideftouchamp),GE_INT};

_export _pitouchcycnub={(char *) &pitouchcycnub,sizeof(pitouchcycnub),GE_INT};
_export _pitouchcycval2={(char *) &pitouchcycval2,sizeof(pitouchcycval2),GE_INT};
_export _pitouchcycval3={(char *) &pitouchcycval3,sizeof(pitouchcycval3),GE_INT};
_export _pitouchcycval4={(char *) &pitouchcycval4,sizeof(pitouchcycval4),GE_INT};
_export _pideftouchcyc={(char *) &pideftouchcyc,sizeof(pideftouchcyc),GE_INT};

_export _pitouchtphasesnub={(char *) &pitouchtphasesnub,sizeof(pitouchtphasesnub),GE_INT};
_export _pitouchtphasesval2={(char *) &pitouchtphasesval2,sizeof(pitouchtphasesval2),GE_INT};
_export _pitouchtphasesval3={(char *) &pitouchtphasesval3,sizeof(pitouchtphasesval3),GE_INT};
_export _pitouchtphasesval4={(char *) &pitouchtphasesval4,sizeof(pitouchtphasesval4),GE_INT};
_export _pideftouchtphases={(char *) &pideftouchtphases,sizeof(pideftouchtphases),GE_INT};

_export _pitouchaxnub={(char *) &pitouchaxnub,sizeof(pitouchaxnub),GE_INT};
_export _pitouchaxval2={(char *) &pitouchaxval2,sizeof(pitouchaxval2),GE_INT};
_export _pitouchaxval3={(char *) &pitouchaxval3,sizeof(pitouchaxval3),GE_INT};
_export _pitouchaxval4={(char *) &pitouchaxval4,sizeof(pitouchaxval4),GE_INT};
_export _pitouchaxval5={(char *) &pitouchaxval5,sizeof(pitouchaxval5),GE_INT};
_export _pideftouchax={(char *) &pideftouchax,sizeof(pideftouchax),GE_INT};

_export _pitouchmenc={(char *) &pitouchmenc,sizeof(pitouchmenc),GE_FLOAT};


_export _pipostlabeldelaynub={(char *) &pipostlabeldelaynub,sizeof(pipostlabeldelaynub),GE_INT};
_export _pipostlabeldelay2={(char *) &pipostlabeldelay2,sizeof(pipostlabeldelay2),GE_FLOAT};
_export _pipostlabeldelay3={(char *) &pipostlabeldelay3,sizeof(pipostlabeldelay3),GE_FLOAT};
_export _pipostlabeldelay4={(char *) &pipostlabeldelay4,sizeof(pipostlabeldelay4),GE_FLOAT};
_export _pipostlabeldelay5={(char *) &pipostlabeldelay5,sizeof(pipostlabeldelay5),GE_FLOAT};
_export _pipostlabeldelay6={(char *) &pipostlabeldelay6,sizeof(pipostlabeldelay6),GE_FLOAT};
_export _pidefpostlabeldelay={(char *) &pidefpostlabeldelay,sizeof(pidefpostlabeldelay),GE_FLOAT};


_export _piphaseimagenub={(char *) &piphaseimagenub,sizeof(piphaseimagenub),GE_INT};
_export _piphaseimageval2={(char *) &piphaseimageval2,sizeof(piphaseimageval2),GE_INT};
_export _piphaseimageval3={(char *) &piphaseimageval3,sizeof(piphaseimageval3),GE_INT};
_export _piphaseimageval4={(char *) &piphaseimageval4,sizeof(piphaseimageval4),GE_INT};


_export _piinplaneres={(char *) &piinplaneres,sizeof(piinplaneres),GE_INT};
_export _ihinplanexres={(char *) &ihinplanexres,sizeof(ihinplanexres),GE_FLOAT};
_export _ihinplaneyres={(char *) &ihinplaneyres,sizeof(ihinplaneyres),GE_FLOAT};


_export _pirbwperpix={(char *) &pirbwperpix,sizeof(pirbwperpix),GE_INT};
_export _ihrbwperpix={(char *) &ihrbwperpix,sizeof(ihrbwperpix),GE_FLOAT};


_export _piesp={(char *) &piesp,sizeof(piesp),GE_INT};
_export _ihesp={(char *) &ihesp,sizeof(ihesp),GE_FLOAT};


_export _piserperph={(char *) &piserperph,sizeof(piserperph),GE_INT};


_export _piapx={(char *) &piapx,sizeof(piapx),GE_INT};
_export _pitbh={(char *) &pitbh,sizeof(pitbh),GE_FLOAT};
_export _pitbhlast={(char *) &pitbhlast,sizeof(pitbhlast),GE_FLOAT};
_export _pinbh={(char *) &pinbh,sizeof(pinbh),GE_INT};
_export _pinbhnub={(char *) &pinbhnub,sizeof(pinbhnub),GE_INT};
_export _pidefnbh={(char *) &pidefnbh,sizeof(pidefnbh),GE_INT};
_export _piapxprfstepnub={(char *) &piapxprfstepnub,sizeof(piapxprfstepnub),GE_INT};
_export _piapxprfstepval1={(char *) &piapxprfstepval1,sizeof(piapxprfstepval1),GE_INT};
_export _piapxprfstepval2={(char *) &piapxprfstepval2,sizeof(piapxprfstepval2),GE_INT};
_export _piapxprfres={(char *) &piapxprfres,sizeof(piapxprfres),GE_INT};
_export _piapxprfacc={(char *) &piapxprfacc,sizeof(piapxprfacc),GE_INT};







_export _cftablemaxspeed={(char *) &cftablemaxspeed,sizeof(cftablemaxspeed),GE_INT};
_export _cftablemaxaccel={(char *) &cftablemaxaccel,sizeof(cftablemaxaccel),GE_INT};
_export _cftablemaxdecel={(char *) &cftablemaxdecel,sizeof(cftablemaxdecel),GE_INT};

_export _cffield={(char *) &cffield,sizeof(cffield),GE_INT};

_export _cflinfrq={(char *) &cflinfrq,sizeof(cflinfrq),GE_FLOAT};
_export _cfhpdl={(char *) &cfhpdl,sizeof(cfhpdl),GE_FLOAT};
_export _cfbpdl={(char *) &cfbpdl,sizeof(cfbpdl),GE_FLOAT};
_export _cfhpsl={(char *) &cfhpsl,sizeof(cfhpsl),GE_FLOAT};
_export _cfbpsl={(char *) &cfbpsl,sizeof(cfbpsl),GE_FLOAT};
_export _cfhpv={(char *) &cfhpv,sizeof(cfhpv),GE_FLOAT};
_export _cfbpv={(char *) &cfbpv,sizeof(cfbpv),GE_FLOAT};
_export _cfhqpc={(char *) &cfhqpc,sizeof(cfhqpc),GE_FLOAT};
_export _cfbqpc={(char *) &cfbqpc,sizeof(cfbqpc),GE_FLOAT};
_export _cfhllr={(char *) &cfhllr,sizeof(cfhllr),GE_FLOAT};
_export _cfbllr={(char *) &cfbllr,sizeof(cfbllr),GE_FLOAT};
_export _cfloss={(char *) &cfloss,sizeof(cfloss),GE_FLOAT};

_export _cfbwmin={(char *) &cfbwmin,sizeof(cfbwmin),GE_INT};
_export _cfbwmin1={(char *) &cfbwmin1,sizeof(cfbwmin1),GE_INT};


_export _cfmaxave={(char *) &cfmaxave,sizeof(cfmaxave),GE_FLOAT};
_export _discretionaryave={(char *) &discretionaryave,sizeof(discretionaryave),GE_FLOAT};
_export _cfmaxavepm={(char *) &cfmaxavepm,sizeof(cfmaxavepm),GE_FLOAT};
_export _cfmaxhave={(char *) &cfmaxhave,sizeof(cfmaxhave),GE_FLOAT};
_export _discretionaryhave={(char *) &discretionaryhave,sizeof(discretionaryhave),GE_FLOAT};
_export _cfmaxextremity={(char *) &cfmaxextremity,sizeof(cfmaxextremity),GE_FLOAT};
_export _cfmaxcave={(char *) &cfmaxcave,sizeof(cfmaxcave),GE_FLOAT};
_export _cfmaxpeak={(char *) &cfmaxpeak,sizeof(cfmaxpeak),GE_FLOAT};
_export _cfmaxepeak={(char *) &cfmaxepeak,sizeof(cfmaxepeak),GE_FLOAT};
_export _cfmaxcpeak={(char *) &cfmaxcpeak,sizeof(cfmaxcpeak),GE_FLOAT};


_export _cfderatingFactorRTSAR={(char *) &cfderatingFactorRTSAR,sizeof(cfderatingFactorRTSAR),GE_FLOAT};

_export _discretionaryPeakB1={(char *) &discretionaryPeakB1,sizeof(discretionaryPeakB1),GE_FLOAT};
_export _discretionaryB1rms={(char *) &discretionaryB1rms,sizeof(discretionaryB1rms),GE_FLOAT};

_export _maxSeriesTime={(char *) &maxSeriesTime,sizeof(maxSeriesTime),GE_FLOAT};




_export _cftpssize={(char *) &cftpssize,sizeof(cftpssize),GE_FLOAT};

_export _cftpsnproc={(char *) &cftpsnproc,sizeof(cftpsnproc),GE_INT};
_export _cftpsproctype={(char *) &cftpsproctype,sizeof(cftpsproctype),GE_INT};


_export _rhrawsize={(char *) &rhrawsize,sizeof(rhrawsize),GE_STRUCT};


_export _cfacqtodisksize={(char *) &cfacqtodisksize,sizeof(cfacqtodisksize),GE_STRUCT};


_export _cfrfMaxAttenuation={(char *) &cfrfMaxAttenuation,sizeof(cfrfMaxAttenuation),GE_INT};

_export _cfdbmax={(char *) &cfdbmax,sizeof(cfdbmax),GE_INT};
_export _cfbbmod={(char *) &cfbbmod,sizeof(cfbbmod),GE_INT};
_export _cftrnew={(char *) &cftrnew,sizeof(cftrnew),GE_INT};
_export _cfrecvst={(char *) &cfrecvst,sizeof(cfrecvst),GE_INT};
_export _cfrecvend={(char *) &cfrecvend,sizeof(cfrecvend),GE_INT};
























_export _cfgradamp={(char *) &cfgradamp,sizeof(cfgradamp),GE_INT};

_export _cfhtdel={(char *) &cfhtdel,sizeof(cfhtdel),GE_INT};
_export _cfcftdel={(char *) &cfcftdel,sizeof(cfcftdel),GE_INT};
_export _cfcgain={(char *) &cfcgain,sizeof(cfcgain),GE_FLOAT};


_export _cfrfrapb={(char *) &cfrfrapb,sizeof(cfrfrapb),GE_INT};
_export _cfrfraph={(char *) &cfrfraph,sizeof(cfrfraph),GE_INT};
_export _cfrfraps={(char *) &cfrfraps,sizeof(cfrfraps),GE_INT};
_export _cfrfrapcw={(char *) &cfrfrapcw,sizeof(cfrfrapcw),GE_INT};
_export _cfrfmapb={(char *) &cfrfmapb,sizeof(cfrfmapb),GE_INT};
_export _cfrfmaph={(char *) &cfrfmaph,sizeof(cfrfmaph),GE_INT};
_export _cfrfmaps={(char *) &cfrfmaps,sizeof(cfrfmaps),GE_INT};
_export _cfrfmpeb={(char *) &cfrfmpeb,sizeof(cfrfmpeb),GE_FLOAT};
_export _cfrfmpeh={(char *) &cfrfmpeh,sizeof(cfrfmpeh),GE_FLOAT};
_export _cfrfmpes={(char *) &cfrfmpes,sizeof(cfrfmpes),GE_FLOAT};
_export _cfrfmpwb={(char *) &cfrfmpwb,sizeof(cfrfmpwb),GE_INT};
_export _cfrfmpwh={(char *) &cfrfmpwh,sizeof(cfrfmpwh),GE_INT};
_export _cfrfmpws={(char *) &cfrfmpws,sizeof(cfrfmpws),GE_INT};
_export _cfrfmdcb={(char *) &cfrfmdcb,sizeof(cfrfmdcb),GE_FLOAT};
_export _cfrfmdch={(char *) &cfrfmdch,sizeof(cfrfmdch),GE_FLOAT};
_export _cfrfmdcs={(char *) &cfrfmdcs,sizeof(cfrfmdcs),GE_FLOAT};
_export _cfrfamptyp={(char *) &cfrfamptyp,sizeof(cfrfamptyp),GE_INT};
_export _cfpwrmontyp={(char *) &cfpwrmontyp,sizeof(cfpwrmontyp),GE_INT};
_export _cfpwrmonreflmeas={(char *) &cfpwrmonreflmeas,sizeof(cfpwrmonreflmeas),GE_INT};

_export _cfpsdgraddly={(char *) &cfpsdgraddly,sizeof(cfpsdgraddly),GE_INT};
_export _cfpsdrfdly={(char *) &cfpsdrfdly,sizeof(cfpsdrfdly),GE_INT};
_export _cfpsdrfdlyx={(char *) &cfpsdrfdlyx,sizeof(cfpsdrfdlyx),GE_INT};
_export _cfpsdrfdlyy={(char *) &cfpsdrfdlyy,sizeof(cfpsdrfdlyy),GE_INT};
_export _cfpsdrfdlyz={(char *) &cfpsdrfdlyz,sizeof(cfpsdrfdlyz),GE_INT};
_export _cfxrdelay={(char *) &cfxrdelay,sizeof(cfxrdelay),GE_INT};
_export _cfyrdelay={(char *) &cfyrdelay,sizeof(cfyrdelay),GE_INT};
_export _cfzrdelay={(char *) &cfzrdelay,sizeof(cfzrdelay),GE_INT};


_export _cfcoilshld={(char *) &cfcoilshld,sizeof(cfcoilshld),GE_INT};

_export _cfrfunblank={(char *) &cfrfunblank,sizeof(cfrfunblank),GE_INT};






_export _cfxfa={(char *) &cfxfa,sizeof(cfxfa),GE_FLOAT};
_export _cfxcc={(char *) &cfxcc,sizeof(cfxcc),GE_FLOAT};

_export _cfyfa={(char *) &cfyfa,sizeof(cfyfa),GE_FLOAT};
_export _cfycc={(char *) &cfycc,sizeof(cfycc),GE_FLOAT};

_export _cfzfa={(char *) &cfzfa,sizeof(cfzfa),GE_FLOAT};
_export _cfzcc={(char *) &cfzcc,sizeof(cfzcc),GE_FLOAT};

_export _cfxgram={(char *) &cfxgram,sizeof(cfxgram),GE_INT};
_export _cfygram={(char *) &cfygram,sizeof(cfygram),GE_INT};
_export _cfzgram={(char *) &cfzgram,sizeof(cfzgram),GE_INT};
_export _cfxasm={(char *) &cfxasm,sizeof(cfxasm),GE_INT};
_export _cfyasm={(char *) &cfyasm,sizeof(cfyasm),GE_INT};
_export _cfzasm={(char *) &cfzasm,sizeof(cfzasm),GE_INT};
_export _cfxgasm={(char *) &cfxgasm,sizeof(cfxgasm),GE_INT};
_export _cfygasm={(char *) &cfygasm,sizeof(cfygasm),GE_INT};
_export _cfzgasm={(char *) &cfzgasm,sizeof(cfzgasm),GE_INT};
_export _cfxseries={(char *) &cfxseries,sizeof(cfxseries),GE_INT};
_export _cfyseries={(char *) &cfyseries,sizeof(cfyseries),GE_INT};
_export _cfzseries={(char *) &cfzseries,sizeof(cfzseries),GE_INT};
_export _cfxnumpower={(char *) &cfxnumpower,sizeof(cfxnumpower),GE_INT};
_export _cfynumpower={(char *) &cfynumpower,sizeof(cfynumpower),GE_INT};
_export _cfznumpower={(char *) &cfznumpower,sizeof(cfznumpower),GE_INT};

_export _cftuning={(char *) &cftuning,sizeof(cftuning),GE_INT};

_export _cfrealtime={(char *) &cfrealtime,sizeof(cfrealtime),GE_INT};

_export _cfcompress={(char *) &cfcompress,sizeof(cfcompress),GE_INT};


_export _cfdbdtts={(char *) &cfdbdtts,sizeof(cfdbdtts),GE_FLOAT};



_export _cfdbdtper={(char *) &cfdbdtper,sizeof(cfdbdtper),GE_FLOAT};
_export _cfdbdtper2={(char *) &cfdbdtper2,sizeof(cfdbdtper2),GE_FLOAT};

_export _pidbdtts={(char *) &pidbdtts,sizeof(pidbdtts),GE_FLOAT};
_export _pidbdtper={(char *) &pidbdtper,sizeof(pidbdtper),GE_FLOAT};
_export _cfgovbody={(char *) &cfgovbody,sizeof(cfgovbody),GE_INT};



_export _cfgcoiltype={(char *) &cfgcoiltype,sizeof(cfgcoiltype),GE_INT};
_export _cfsrmode={(char *) &cfsrmode,sizeof(cfsrmode),GE_INT};

_export _cfgpeakirms={(char *) &cfgpeakirms,sizeof(cfgpeakirms),GE_FLOAT};
_export _cfgcontirms={(char *) &cfgcontirms,sizeof(cfgcontirms),GE_FLOAT};
_export _cfgburstime={(char *) &cfgburstime,sizeof(cfgburstime),GE_FLOAT};

_export _cfxirms={(char *) &cfxirms,sizeof(cfxirms),GE_FLOAT};
_export _cfyirms={(char *) &cfyirms,sizeof(cfyirms),GE_FLOAT};
_export _cfzirms={(char *) &cfzirms,sizeof(cfzirms),GE_FLOAT};

_export _cfxipeak={(char *) &cfxipeak,sizeof(cfxipeak),GE_FLOAT};
_export _cfyipeak={(char *) &cfyipeak,sizeof(cfyipeak),GE_FLOAT};
_export _cfzipeak={(char *) &cfzipeak,sizeof(cfzipeak),GE_FLOAT};

_export _cfrmp2xfs={(char *) &cfrmp2xfs,sizeof(cfrmp2xfs),GE_INT};
_export _cfrmp2yfs={(char *) &cfrmp2yfs,sizeof(cfrmp2yfs),GE_INT};
_export _cfrmp2zfs={(char *) &cfrmp2zfs,sizeof(cfrmp2zfs),GE_INT};

_export _cffall2x0={(char *) &cffall2x0,sizeof(cffall2x0),GE_INT};
_export _cffall2y0={(char *) &cffall2y0,sizeof(cffall2y0),GE_INT};
_export _cffall2z0={(char *) &cffall2z0,sizeof(cffall2z0),GE_INT};

_export _cfxfs={(char *) &cfxfs,sizeof(cfxfs),GE_FLOAT};
_export _cfyfs={(char *) &cfyfs,sizeof(cfyfs),GE_FLOAT};
_export _cfzfs={(char *) &cfzfs,sizeof(cfzfs),GE_FLOAT};

_export _cfxfull={(char *) &cfxfull,sizeof(cfxfull),GE_INT};
_export _cfyfull={(char *) &cfyfull,sizeof(cfyfull),GE_INT};
_export _cfzfull={(char *) &cfzfull,sizeof(cfzfull),GE_INT};

_export _cfxbeta={(char *) &cfxbeta,sizeof(cfxbeta),GE_FLOAT};
_export _cfybeta={(char *) &cfybeta,sizeof(cfybeta),GE_FLOAT};
_export _cfzbeta={(char *) &cfzbeta,sizeof(cfzbeta),GE_FLOAT};



_export _cfxamptran={(char *) &cfxamptran,sizeof(cfxamptran),GE_FLOAT};
_export _cfyamptran={(char *) &cfyamptran,sizeof(cfyamptran),GE_FLOAT};
_export _cfzamptran={(char *) &cfzamptran,sizeof(cfzamptran),GE_FLOAT};

_export _cfxiavrgabs={(char *) &cfxiavrgabs,sizeof(cfxiavrgabs),GE_FLOAT};
_export _cfyiavrgabs={(char *) &cfyiavrgabs,sizeof(cfyiavrgabs),GE_FLOAT};
_export _cfziavrgabs={(char *) &cfziavrgabs,sizeof(cfziavrgabs),GE_FLOAT};

_export _cfxirmspos={(char *) &cfxirmspos,sizeof(cfxirmspos),GE_FLOAT};
_export _cfyirmspos={(char *) &cfyirmspos,sizeof(cfyirmspos),GE_FLOAT};
_export _cfzirmspos={(char *) &cfzirmspos,sizeof(cfzirmspos),GE_FLOAT};

_export _cfxirmsneg={(char *) &cfxirmsneg,sizeof(cfxirmsneg),GE_FLOAT};
_export _cfyirmsneg={(char *) &cfyirmsneg,sizeof(cfyirmsneg),GE_FLOAT};
_export _cfzirmsneg={(char *) &cfzirmsneg,sizeof(cfzirmsneg),GE_FLOAT};

_export _cfxpwmdc={(char *) &cfxpwmdc,sizeof(cfxpwmdc),GE_FLOAT};
_export _cfypwmdc={(char *) &cfypwmdc,sizeof(cfypwmdc),GE_FLOAT};
_export _cfzpwmdc={(char *) &cfzpwmdc,sizeof(cfzpwmdc),GE_FLOAT};


_export _cfrmp2xfsfw={(char *) &cfrmp2xfsfw,sizeof(cfrmp2xfsfw),GE_INT};
_export _cfrmp2yfsfw={(char *) &cfrmp2yfsfw,sizeof(cfrmp2yfsfw),GE_INT};
_export _cfrmp2zfsfw={(char *) &cfrmp2zfsfw,sizeof(cfrmp2zfsfw),GE_INT};
_export _cffall2x0fw={(char *) &cffall2x0fw,sizeof(cffall2x0fw),GE_INT};
_export _cffall2y0fw={(char *) &cffall2y0fw,sizeof(cffall2y0fw),GE_INT};
_export _cffall2z0fw={(char *) &cffall2z0fw,sizeof(cffall2z0fw),GE_INT};


_export _cfdbdtdx={(char *) &cfdbdtdx,sizeof(cfdbdtdx),GE_FLOAT};
_export _cfdbdtdy={(char *) &cfdbdtdy,sizeof(cfdbdtdy),GE_FLOAT};
_export _cfdbdtdz={(char *) &cfdbdtdz,sizeof(cfdbdtdz),GE_FLOAT};


_export _cfzoomlim_fov={(char *) &cfzoomlim_fov,sizeof(cfzoomlim_fov),GE_INT};
_export _cfzoomlim_ofc={(char *) &cfzoomlim_ofc,sizeof(cfzoomlim_ofc),GE_INT};
_export _cfzoomlim_ctl={(char *) &cfzoomlim_ctl,sizeof(cfzoomlim_ctl),GE_INT};



_export _sigrammode={(char *) &sigrammode,sizeof(sigrammode),GE_INT};

_export _cfsrmodeconv={(char *) &cfsrmodeconv,sizeof(cfsrmodeconv),GE_FLOAT};
_export _cfsrmodeact={(char *) &cfsrmodeact,sizeof(cfsrmodeact),GE_FLOAT};
_export _cfopenmagnet={(char *) &cfopenmagnet,sizeof(cfopenmagnet),GE_INT};
_export _cftableanglex={(char *) &cftableanglex,sizeof(cftableanglex),GE_FLOAT};
_export _cftableangley={(char *) &cftableangley,sizeof(cftableangley),GE_FLOAT};
_export _cftableanglez={(char *) &cftableanglez,sizeof(cftableanglez),GE_FLOAT};
_export _cftableoffsetx={(char *) &cftableoffsetx,sizeof(cftableoffsetx),GE_FLOAT};
_export _cftableoffsety={(char *) &cftableoffsety,sizeof(cftableoffsety),GE_FLOAT};
_export _cftableoffsetz={(char *) &cftableoffsetz,sizeof(cftableoffsetz),GE_FLOAT};


_export _cfmaxb1rmshead={(char *) &cfmaxb1rmshead,sizeof(cfmaxb1rmshead),GE_FLOAT};



_export _cfxmgrampow={(char *) &cfxmgrampow,sizeof(cfxmgrampow),GE_FLOAT};
_export _cfymgrampow={(char *) &cfymgrampow,sizeof(cfymgrampow),GE_FLOAT};
_export _cfzmgrampow={(char *) &cfzmgrampow,sizeof(cfzmgrampow),GE_FLOAT};
_export _cfsdlim={(char *) &cfsdlim,sizeof(cfsdlim),GE_FLOAT};
_export _cfxrsat={(char *) &cfxrsat,sizeof(cfxrsat),GE_FLOAT};
_export _cfyrsat={(char *) &cfyrsat,sizeof(cfyrsat),GE_FLOAT};
_export _cfzrsat={(char *) &cfzrsat,sizeof(cfzrsat),GE_FLOAT};
_export _cfxvsat={(char *) &cfxvsat,sizeof(cfxvsat),GE_FLOAT};
_export _cfyvsat={(char *) &cfyvsat,sizeof(cfyvsat),GE_FLOAT};
_export _cfzvsat={(char *) &cfzvsat,sizeof(cfzvsat),GE_FLOAT};
_export _cfgpmpow={(char *) &cfgpmpow,sizeof(cfgpmpow),GE_FLOAT};
_export _cfmgps={(char *) &cfmgps,sizeof(cfmgps),GE_FLOAT};
_export _cfvhr={(char *) &cfvhr,sizeof(cfvhr),GE_FLOAT};
_export _cfrcoil={(char *) &cfrcoil,sizeof(cfrcoil),GE_FLOAT};
_export _cflcoil={(char *) &cflcoil,sizeof(cflcoil),GE_FLOAT};
_export _cfraccoil={(char *) &cfraccoil,sizeof(cfraccoil),GE_FLOAT};
_export _cfpmgs={(char *) &cfpmgs,sizeof(cfpmgs),GE_FLOAT};
_export _cfrhr={(char *) &cfrhr,sizeof(cfrhr),GE_FLOAT};
_export _cfxvpwm={(char *) &cfxvpwm,sizeof(cfxvpwm),GE_FLOAT};
_export _cfyvpwm={(char *) &cfyvpwm,sizeof(cfyvpwm),GE_FLOAT};
_export _cfzvpwm={(char *) &cfzvpwm,sizeof(cfzvpwm),GE_FLOAT};
_export _cfmaxbw={(char *) &cfmaxbw,sizeof(cfmaxbw),GE_FLOAT};
_export _cfnumrcvrs={(char *) &cfnumrcvrs,sizeof(cfnumrcvrs),GE_INT};


_export _cffastprescan={(char *) &cffastprescan,sizeof(cffastprescan),GE_INT};




_export _cfcoilDC_gain={(char *) &cfcoilDC_gain,sizeof(cfcoilDC_gain),GE_FLOAT};
_export _cfcoilDC_Rx={(char *) &cfcoilDC_Rx,sizeof(cfcoilDC_Rx),GE_FLOAT};
_export _cfcoilDC_Ry={(char *) &cfcoilDC_Ry,sizeof(cfcoilDC_Ry),GE_FLOAT};
_export _cfcoilDC_Rz={(char *) &cfcoilDC_Rz,sizeof(cfcoilDC_Rz),GE_FLOAT};
_export _cfcoilDC_Lx={(char *) &cfcoilDC_Lx,sizeof(cfcoilDC_Lx),GE_FLOAT};
_export _cfcoilDC_Ly={(char *) &cfcoilDC_Ly,sizeof(cfcoilDC_Ly),GE_FLOAT};
_export _cfcoilDC_Lz={(char *) &cfcoilDC_Lz,sizeof(cfcoilDC_Lz),GE_FLOAT};

_export _cfcoilAC_gain={(char *) &cfcoilAC_gain,sizeof(cfcoilAC_gain),GE_FLOAT};
_export _cfcoilAC_power={(char *) &cfcoilAC_power,sizeof(cfcoilAC_power),GE_FLOAT};
_export _cfcoilAC_power_1axis={(char *) &cfcoilAC_power_1axis,sizeof(cfcoilAC_power_1axis),GE_FLOAT};
_export _cfcoilAC_power_burst={(char *) &cfcoilAC_power_burst,sizeof(cfcoilAC_power_burst),GE_FLOAT};
_export _cfcoilAC_temp_base_burst={(char *) &cfcoilAC_temp_base_burst,sizeof(cfcoilAC_temp_base_burst),GE_FLOAT};
_export _cfcoilAC_temp_limit_burst={(char *) &cfcoilAC_temp_limit_burst,sizeof(cfcoilAC_temp_limit_burst),GE_FLOAT};
_export _cfcoilAC_timeconstant_burst={(char *) &cfcoilAC_timeconstant_burst,sizeof(cfcoilAC_timeconstant_burst),GE_FLOAT};
_export _cfcoilAC_RxA={(char *) &cfcoilAC_RxA,sizeof(cfcoilAC_RxA),GE_FLOAT};
_export _cfcoilAC_RyA={(char *) &cfcoilAC_RyA,sizeof(cfcoilAC_RyA),GE_FLOAT};
_export _cfcoilAC_RzA={(char *) &cfcoilAC_RzA,sizeof(cfcoilAC_RzA),GE_FLOAT};
_export _cfcoilAC_RxB={(char *) &cfcoilAC_RxB,sizeof(cfcoilAC_RxB),GE_FLOAT};
_export _cfcoilAC_RyB={(char *) &cfcoilAC_RyB,sizeof(cfcoilAC_RyB),GE_FLOAT};
_export _cfcoilAC_RzB={(char *) &cfcoilAC_RzB,sizeof(cfcoilAC_RzB),GE_FLOAT};
_export _cfcoilAC_RxC={(char *) &cfcoilAC_RxC,sizeof(cfcoilAC_RxC),GE_FLOAT};
_export _cfcoilAC_RyC={(char *) &cfcoilAC_RyC,sizeof(cfcoilAC_RyC),GE_FLOAT};
_export _cfcoilAC_RzC={(char *) &cfcoilAC_RzC,sizeof(cfcoilAC_RzC),GE_FLOAT};

_export _cfcoilAC_lumpR1x={(char *) &cfcoilAC_lumpR1x,sizeof(cfcoilAC_lumpR1x),GE_FLOAT};
_export _cfcoilAC_lumpR1y={(char *) &cfcoilAC_lumpR1y,sizeof(cfcoilAC_lumpR1y),GE_FLOAT};
_export _cfcoilAC_lumpR1z={(char *) &cfcoilAC_lumpR1z,sizeof(cfcoilAC_lumpR1z),GE_FLOAT};
_export _cfcoilAC_lumpL2x={(char *) &cfcoilAC_lumpL2x,sizeof(cfcoilAC_lumpL2x),GE_FLOAT};
_export _cfcoilAC_lumpL2y={(char *) &cfcoilAC_lumpL2y,sizeof(cfcoilAC_lumpL2y),GE_FLOAT};
_export _cfcoilAC_lumpL2z={(char *) &cfcoilAC_lumpL2z,sizeof(cfcoilAC_lumpL2z),GE_FLOAT};
_export _cfcoilAC_lumpR3x={(char *) &cfcoilAC_lumpR3x,sizeof(cfcoilAC_lumpR3x),GE_FLOAT};
_export _cfcoilAC_lumpR3y={(char *) &cfcoilAC_lumpR3y,sizeof(cfcoilAC_lumpR3y),GE_FLOAT};
_export _cfcoilAC_lumpR3z={(char *) &cfcoilAC_lumpR3z,sizeof(cfcoilAC_lumpR3z),GE_FLOAT};
_export _cfcoilAC_lumpL4x={(char *) &cfcoilAC_lumpL4x,sizeof(cfcoilAC_lumpL4x),GE_FLOAT};
_export _cfcoilAC_lumpL4y={(char *) &cfcoilAC_lumpL4y,sizeof(cfcoilAC_lumpL4y),GE_FLOAT};
_export _cfcoilAC_lumpL4z={(char *) &cfcoilAC_lumpL4z,sizeof(cfcoilAC_lumpL4z),GE_FLOAT};
_export _cfcoilAC_lumpR5x={(char *) &cfcoilAC_lumpR5x,sizeof(cfcoilAC_lumpR5x),GE_FLOAT};
_export _cfcoilAC_lumpR5y={(char *) &cfcoilAC_lumpR5y,sizeof(cfcoilAC_lumpR5y),GE_FLOAT};
_export _cfcoilAC_lumpR5z={(char *) &cfcoilAC_lumpR5z,sizeof(cfcoilAC_lumpR5z),GE_FLOAT};
_export _cfcoilAC_timeres={(char *) &cfcoilAC_timeres,sizeof(cfcoilAC_timeres),GE_FLOAT};
_export _cfcoilAC_fftpoints={(char *) &cfcoilAC_fftpoints,sizeof(cfcoilAC_fftpoints),GE_INT};

_export _cfcoilAC_xgain={(char *) &cfcoilAC_xgain,sizeof(cfcoilAC_xgain),GE_FLOAT};
_export _cfcoilAC_ygain={(char *) &cfcoilAC_ygain,sizeof(cfcoilAC_ygain),GE_FLOAT};
_export _cfcoilAC_zgain={(char *) &cfcoilAC_zgain,sizeof(cfcoilAC_zgain),GE_FLOAT};

_export _cfcoilQAC_A0={(char *) &cfcoilQAC_A0,sizeof(cfcoilQAC_A0),GE_FLOAT};
_export _cfcoilQAC_A1={(char *) &cfcoilQAC_A1,sizeof(cfcoilQAC_A1),GE_FLOAT};
_export _cfcoilQAC_A2={(char *) &cfcoilQAC_A2,sizeof(cfcoilQAC_A2),GE_FLOAT};
_export _cfcoilQAC_A3={(char *) &cfcoilQAC_A3,sizeof(cfcoilQAC_A3),GE_FLOAT};
_export _cfcoilQAC_A4={(char *) &cfcoilQAC_A4,sizeof(cfcoilQAC_A4),GE_FLOAT};
_export _cfcoilQAC_A5={(char *) &cfcoilQAC_A5,sizeof(cfcoilQAC_A5),GE_FLOAT};
_export _cfcoilQAC_A6={(char *) &cfcoilQAC_A6,sizeof(cfcoilQAC_A6),GE_FLOAT};
_export _cfcoilQAC_Xcoef={(char *) &cfcoilQAC_Xcoef,sizeof(cfcoilQAC_Xcoef),GE_FLOAT};
_export _cfcoilQAC_Ycoef={(char *) &cfcoilQAC_Ycoef,sizeof(cfcoilQAC_Ycoef),GE_FLOAT};
_export _cfcoilQAC_Zcoef={(char *) &cfcoilQAC_Zcoef,sizeof(cfcoilQAC_Zcoef),GE_FLOAT};
_export _cfcoilQAC_maxtime={(char *) &cfcoilQAC_maxtime,sizeof(cfcoilQAC_maxtime),GE_FLOAT};
_export _cfcoilQAC_const={(char *) &cfcoilQAC_const,sizeof(cfcoilQAC_const),GE_FLOAT};
_export _cfcoilQAC_heat_maxtime={(char *) &cfcoilQAC_heat_maxtime,sizeof(cfcoilQAC_heat_maxtime),GE_FLOAT};
_export _cfcoilQAC_heat_slope={(char *) &cfcoilQAC_heat_slope,sizeof(cfcoilQAC_heat_slope),GE_FLOAT};
_export _cfcoilQAC_heat_const={(char *) &cfcoilQAC_heat_const,sizeof(cfcoilQAC_heat_const),GE_FLOAT};

_export _cfxgd_timeres={(char *) &cfxgd_timeres,sizeof(cfxgd_timeres),GE_FLOAT};
_export _cfxgd_cableirmslimit={(char *) &cfxgd_cableirmslimit,sizeof(cfxgd_cableirmslimit),GE_FLOAT};
_export _cfxgd_cableirmslimit_burst={(char *) &cfxgd_cableirmslimit_burst,sizeof(cfxgd_cableirmslimit_burst),GE_FLOAT};
_export _cfxgd_cabletimeconstant_burst={(char *) &cfxgd_cabletimeconstant_burst,sizeof(cfxgd_cabletimeconstant_burst),GE_FLOAT};
_export _cfxgd_busbartemplimit={(char *) &cfxgd_busbartemplimit,sizeof(cfxgd_busbartemplimit),GE_FLOAT};
_export _cfxgd_chokepowerlimit={(char *) &cfxgd_chokepowerlimit,sizeof(cfxgd_chokepowerlimit),GE_FLOAT};

_export _cfxps_avglvpwrlimit={(char *) &cfxps_avglvpwrlimit,sizeof(cfxps_avglvpwrlimit),GE_FLOAT};
_export _cfxps_avghvpwrlimit={(char *) &cfxps_avghvpwrlimit,sizeof(cfxps_avghvpwrlimit),GE_FLOAT};
_export _cfxps_avgpdulimit={(char *) &cfxps_avgpdulimit,sizeof(cfxps_avgpdulimit),GE_FLOAT};
_export _cfxgd_IGBTtemplimit={(char *) &cfxgd_IGBTtemplimit,sizeof(cfxgd_IGBTtemplimit),GE_FLOAT};
_export _cfxfd_power_limit={(char *) &cfxfd_power_limit,sizeof(cfxfd_power_limit),GE_FLOAT};
_export _cfxfd_temp_limit={(char *) &cfxfd_temp_limit,sizeof(cfxfd_temp_limit),GE_FLOAT};




_export _cfsystemmaxfov={(char *) &cfsystemmaxfov,sizeof(cfsystemmaxfov),GE_FLOAT};













_export _cfcerdtype={(char *) &cfcerdtype,sizeof(cfcerdtype),GE_INT};


_export _cfpicture={(char *) &cfpicture,sizeof(cfpicture),GE_INT};

_export _cfspectroPMcal={(char *) &cfspectroPMcal,sizeof(cfspectroPMcal),GE_FLOAT};


_export _rec_mode={(char *) &rec_mode,sizeof(rec_mode),GE_INT};

_export _opnewgeo={(char *) &opnewgeo,sizeof(opnewgeo),GE_INT};




_export _simulation={(char *) &simulation,sizeof(simulation),GE_INT};


_export _csi_grid_on={(char *) &csi_grid_on,sizeof(csi_grid_on),GE_INT};
_export _pispecprescan={(char *) &pispecprescan,sizeof(pispecprescan),GE_INT};











_export _picsimode={(char *) &picsimode,sizeof(picsimode),GE_INT};

_export _rhrlfov={(char *) &rhrlfov,sizeof(rhrlfov),GE_INT};
_export _rhapfov={(char *) &rhapfov,sizeof(rhapfov),GE_INT};
_export _rhsifov={(char *) &rhsifov,sizeof(rhsifov),GE_INT};

_export _pitracqnub={(char *) &pitracqnub,sizeof(pitracqnub),GE_INT};
_export _pitracqval2={(char *) &pitracqval2,sizeof(pitracqval2),GE_INT};
_export _pitracqval3={(char *) &pitracqval3,sizeof(pitracqval3),GE_INT};
_export _pitracqval4={(char *) &pitracqval4,sizeof(pitracqval4),GE_INT};
_export _pitracqval5={(char *) &pitracqval5,sizeof(pitracqval5),GE_INT};
_export _pitracqval6={(char *) &pitracqval6,sizeof(pitracqval6),GE_INT};


_export _picoilfastswitchrequired={(char *) &picoilfastswitchrequired,sizeof(picoilfastswitchrequired),GE_INT};














_export 





















_coilInfo={(char *) coilInfo,sizeof(coilInfo),GE_STRUCT};

_export 





















_volRecCoilInfo={(char *) volRecCoilInfo,sizeof(volRecCoilInfo),GE_STRUCT};

_export 

















_txCoilInfo={(char *) txCoilInfo,sizeof(txCoilInfo),GE_STRUCT};







_export _cfNbTransmitSelect={(char *) &cfNbTransmitSelect,sizeof(cfNbTransmitSelect),GE_INT};
_export _cfBbTransmitSelect={(char *) &cfBbTransmitSelect,sizeof(cfBbTransmitSelect),GE_INT};
_export _cfMnsConverterSelect={(char *) &cfMnsConverterSelect,sizeof(cfMnsConverterSelect),GE_INT};


_export 









_bvalstab={(char *) bvalstab,sizeof(bvalstab),GE_STRUCT};

_export 
_synbvalstab={(char *) synbvalstab,sizeof(synbvalstab),GE_STRUCT};

_export 




_difnextab={(char *) difnextab,sizeof(difnextab),GE_STRUCT};

_export 

























_difnextab_opt={(char *) difnextab_opt,sizeof(difnextab_opt),GE_STRUCT};


_export 



_rhrcmavric_b0_offset={(char *) rhrcmavric_b0_offset,sizeof(rhrcmavric_b0_offset),GE_STRUCT};




_export _aslnextab={(char *) aslnextab,sizeof(aslnextab),GE_STRUCT};
_export _aslimgtab={(char *) aslimgtab,sizeof(aslimgtab),GE_STRUCT};


_export _piaccelscrn={(char *) &piaccelscrn,sizeof(piaccelscrn),GE_INT};
_export _piaccel_total_stride={(char *) &piaccel_total_stride,sizeof(piaccel_total_stride),GE_FLOAT};

_export _cfaccel_ph_maxstride={(char *) &cfaccel_ph_maxstride,sizeof(cfaccel_ph_maxstride),GE_FLOAT};
_export _cfaccel_sl_maxstride={(char *) &cfaccel_sl_maxstride,sizeof(cfaccel_sl_maxstride),GE_FLOAT};
_export _cfaccel_cs_maxstride={(char *) &cfaccel_cs_maxstride,sizeof(cfaccel_cs_maxstride),GE_FLOAT};

_export _accel_ph_stride={(char *) &accel_ph_stride,sizeof(accel_ph_stride),GE_FLOAT};
_export _accel_sl_stride={(char *) &accel_sl_stride,sizeof(accel_sl_stride),GE_FLOAT};
_export _accel_ph_defstride={(char *) &accel_ph_defstride,sizeof(accel_ph_defstride),GE_FLOAT};
_export _accel_sl_defstride={(char *) &accel_sl_defstride,sizeof(accel_sl_defstride),GE_FLOAT};

_export _piaccel_ph_stride={(char *) &piaccel_ph_stride,sizeof(piaccel_ph_stride),GE_FLOAT};
_export _piaccel_phnub={(char *) &piaccel_phnub,sizeof(piaccel_phnub),GE_INT};
_export _piaccel_phedit={(char *) &piaccel_phedit,sizeof(piaccel_phedit),GE_INT};
_export _piaccel_phval2={(char *) &piaccel_phval2,sizeof(piaccel_phval2),GE_FLOAT};
_export _piaccel_phval3={(char *) &piaccel_phval3,sizeof(piaccel_phval3),GE_FLOAT};
_export _piaccel_phval4={(char *) &piaccel_phval4,sizeof(piaccel_phval4),GE_FLOAT};
_export _piaccel_phval5={(char *) &piaccel_phval5,sizeof(piaccel_phval5),GE_FLOAT};
_export _piaccel_phval6={(char *) &piaccel_phval6,sizeof(piaccel_phval6),GE_FLOAT};

_export _piaccel_sl_stride={(char *) &piaccel_sl_stride,sizeof(piaccel_sl_stride),GE_FLOAT};
_export _piaccel_slnub={(char *) &piaccel_slnub,sizeof(piaccel_slnub),GE_INT};
_export _piaccel_sledit={(char *) &piaccel_sledit,sizeof(piaccel_sledit),GE_INT};
_export _piaccel_slval2={(char *) &piaccel_slval2,sizeof(piaccel_slval2),GE_FLOAT};
_export _piaccel_slval3={(char *) &piaccel_slval3,sizeof(piaccel_slval3),GE_FLOAT};
_export _piaccel_slval4={(char *) &piaccel_slval4,sizeof(piaccel_slval4),GE_FLOAT};
_export _piaccel_slval5={(char *) &piaccel_slval5,sizeof(piaccel_slval5),GE_FLOAT};
_export _piaccel_slval6={(char *) &piaccel_slval6,sizeof(piaccel_slval6),GE_FLOAT};

_export _piaccel_t_stride={(char *) &piaccel_t_stride,sizeof(piaccel_t_stride),GE_FLOAT};
_export _piaccel_tnub={(char *) &piaccel_tnub,sizeof(piaccel_tnub),GE_INT};
_export _piaccel_tedit={(char *) &piaccel_tedit,sizeof(piaccel_tedit),GE_INT};
_export _piaccel_tval2={(char *) &piaccel_tval2,sizeof(piaccel_tval2),GE_FLOAT};
_export _piaccel_tval3={(char *) &piaccel_tval3,sizeof(piaccel_tval3),GE_FLOAT};
_export _piaccel_tval4={(char *) &piaccel_tval4,sizeof(piaccel_tval4),GE_FLOAT};
_export _piaccel_tval5={(char *) &piaccel_tval5,sizeof(piaccel_tval5),GE_FLOAT};
_export _piaccel_tval6={(char *) &piaccel_tval6,sizeof(piaccel_tval6),GE_FLOAT};

_export _avminaccel_ph_stride={(char *) &avminaccel_ph_stride,sizeof(avminaccel_ph_stride),GE_FLOAT};
_export _avminaccel_sl_stride={(char *) &avminaccel_sl_stride,sizeof(avminaccel_sl_stride),GE_FLOAT};
_export _avminaccel_t_stride={(char *) &avminaccel_t_stride,sizeof(avminaccel_t_stride),GE_FLOAT};
_export _avmaxaccel_ph_stride={(char *) &avmaxaccel_ph_stride,sizeof(avmaxaccel_ph_stride),GE_FLOAT};
_export _avmaxaccel_sl_stride={(char *) &avmaxaccel_sl_stride,sizeof(avmaxaccel_sl_stride),GE_FLOAT};
_export _avmaxaccel_t_stride={(char *) &avmaxaccel_t_stride,sizeof(avmaxaccel_t_stride),GE_FLOAT};

_export _avminaccel_mb_stride={(char *) &avminaccel_mb_stride,sizeof(avminaccel_mb_stride),GE_FLOAT};
_export _avmaxaccel_mb_stride={(char *) &avmaxaccel_mb_stride,sizeof(avmaxaccel_mb_stride),GE_FLOAT};

_export _avminaccel_cs_stride={(char *) &avminaccel_cs_stride,sizeof(avminaccel_cs_stride),GE_FLOAT};
_export _avmaxaccel_cs_stride={(char *) &avmaxaccel_cs_stride,sizeof(avmaxaccel_cs_stride),GE_FLOAT};

_export _avminaccel_kt_stride={(char *) &avminaccel_kt_stride,sizeof(avminaccel_kt_stride),GE_FLOAT};
_export _avmaxaccel_kt_stride={(char *) &avmaxaccel_kt_stride,sizeof(avmaxaccel_kt_stride),GE_FLOAT};

_export _piaccel_ph_step={(char *) &piaccel_ph_step,sizeof(piaccel_ph_step),GE_FLOAT};
_export _piaccel_sl_step={(char *) &piaccel_sl_step,sizeof(piaccel_sl_step),GE_FLOAT};
_export _piaccel_t_step={(char *) &piaccel_t_step,sizeof(piaccel_t_step),GE_FLOAT};
_export _piaccel_mb_step={(char *) &piaccel_mb_step,sizeof(piaccel_mb_step),GE_INT};
_export _piaccel_cs_step={(char *) &piaccel_cs_step,sizeof(piaccel_cs_step),GE_FLOAT};
_export _piaccel_kt_step={(char *) &piaccel_kt_step,sizeof(piaccel_kt_step),GE_INT};

_export _pimb={(char *) &pimb,sizeof(pimb),GE_INT};
_export _piaccel_mb_stride={(char *) &piaccel_mb_stride,sizeof(piaccel_mb_stride),GE_INT};
_export _piaccel_mbnub={(char *) &piaccel_mbnub,sizeof(piaccel_mbnub),GE_INT};
_export _piaccel_mbedit={(char *) &piaccel_mbedit,sizeof(piaccel_mbedit),GE_INT};
_export _piaccel_mbval2={(char *) &piaccel_mbval2,sizeof(piaccel_mbval2),GE_INT};
_export _piaccel_mbval3={(char *) &piaccel_mbval3,sizeof(piaccel_mbval3),GE_INT};
_export _piaccel_mbval4={(char *) &piaccel_mbval4,sizeof(piaccel_mbval4),GE_INT};
_export _piaccel_mbval5={(char *) &piaccel_mbval5,sizeof(piaccel_mbval5),GE_INT};
_export _piaccel_mbval6={(char *) &piaccel_mbval6,sizeof(piaccel_mbval6),GE_INT};

_export _pics={(char *) &pics,sizeof(pics),GE_INT};
_export _piaccel_cs_stride={(char *) &piaccel_cs_stride,sizeof(piaccel_cs_stride),GE_FLOAT};
_export _piaccel_csnub={(char *) &piaccel_csnub,sizeof(piaccel_csnub),GE_INT};
_export _piaccel_csedit={(char *) &piaccel_csedit,sizeof(piaccel_csedit),GE_INT};
_export _piaccel_csval2={(char *) &piaccel_csval2,sizeof(piaccel_csval2),GE_FLOAT};
_export _piaccel_csval3={(char *) &piaccel_csval3,sizeof(piaccel_csval3),GE_FLOAT};
_export _piaccel_csval4={(char *) &piaccel_csval4,sizeof(piaccel_csval4),GE_FLOAT};
_export _piaccel_csval5={(char *) &piaccel_csval5,sizeof(piaccel_csval5),GE_FLOAT};
_export _piaccel_csval6={(char *) &piaccel_csval6,sizeof(piaccel_csval6),GE_FLOAT};

_export _pikt={(char *) &pikt,sizeof(pikt),GE_INT};
_export _piaccel_kt_stride={(char *) &piaccel_kt_stride,sizeof(piaccel_kt_stride),GE_INT};
_export _piaccel_ktnub={(char *) &piaccel_ktnub,sizeof(piaccel_ktnub),GE_INT};
_export _piaccel_ktedit={(char *) &piaccel_ktedit,sizeof(piaccel_ktedit),GE_INT};
_export _piaccel_ktval2={(char *) &piaccel_ktval2,sizeof(piaccel_ktval2),GE_INT};
_export _piaccel_ktval3={(char *) &piaccel_ktval3,sizeof(piaccel_ktval3),GE_INT};
_export _piaccel_ktval4={(char *) &piaccel_ktval4,sizeof(piaccel_ktval4),GE_INT};
_export _piaccel_ktval5={(char *) &piaccel_ktval5,sizeof(piaccel_ktval5),GE_INT};
_export _piaccel_ktval6={(char *) &piaccel_ktval6,sizeof(piaccel_ktval6),GE_INT};






_export _piarccoilrestrict={(char *) &piarccoilrestrict,sizeof(piarccoilrestrict),GE_INT};


_export _chksum_rhdacqctrl={(char *) &chksum_rhdacqctrl,sizeof(chksum_rhdacqctrl),GE_STRUCT};
_export _chksum_scaninfo={(char *) &chksum_scaninfo,sizeof(chksum_scaninfo),GE_STRUCT};
_export _chksum_rampdir={(char *) &chksum_rampdir,sizeof(chksum_rampdir),GE_INT};





_export _picontrastwarning={(char *) &picontrastwarning,sizeof(picontrastwarning),GE_INT};

_export _piexcitemodenub={(char *) &piexcitemodenub,sizeof(piexcitemodenub),GE_INT};
_export _pidefexcitemode={(char *) &pidefexcitemode,sizeof(pidefexcitemode),GE_INT};
_export _cframpdir={(char *) &cframpdir,sizeof(cframpdir),GE_INT};

_export _pihoeccvis={(char *) &pihoeccvis,sizeof(pihoeccvis),GE_INT};
_export _pihoeccnub={(char *) &pihoeccnub,sizeof(pihoeccnub),GE_INT};


_export _cfmaxb1ref={(char *) &cfmaxb1ref,sizeof(cfmaxb1ref),GE_FLOAT};
_export _xmtaddRef={(char *) &xmtaddRef,sizeof(xmtaddRef),GE_FLOAT};

_export _piinvertfnub={(char *) &piinvertfnub,sizeof(piinvertfnub),GE_INT};
_export _piinvertfvis={(char *) &piinvertfvis,sizeof(piinvertfvis),GE_INT};


_export _piaddscannub={(char *) &piaddscannub,sizeof(piaddscannub),GE_INT};
_export _piaddscantype={(char *) &piaddscantype,sizeof(piaddscantype),GE_INT};
_export _cfscoutscanact={(char *) &cfscoutscanact,sizeof(cfscoutscanact),GE_INT};


_export _body_sar_table={(char *) body_sar_table,sizeof(body_sar_table),GE_STRUCT};
_export _head_sar_table={(char *) head_sar_table,sizeof(head_sar_table),GE_STRUCT};
_export _extremity_sar_table={(char *) extremity_sar_table,sizeof(extremity_sar_table),GE_STRUCT};





_export _topofhead={(char *) &topofhead,sizeof(topofhead),GE_STRUCT};
_export _piscan_distance_toh={(char *) &piscan_distance_toh,sizeof(piscan_distance_toh),GE_FLOAT};
_export _pipdhs_active={(char *) &pipdhs_active,sizeof(pipdhs_active),GE_INT};


_export _cfOptimalSnrRecon={(char *) &cfOptimalSnrRecon,sizeof(cfOptimalSnrRecon),GE_INT};
_export _cfVirtualChannelRecon={(char *) &cfVirtualChannelRecon,sizeof(cfVirtualChannelRecon),GE_INT};



#endif /* h_ksfse_exportstr_h */

