/*
 * ksfse.cnvendian.input.c
 *
 * This file is automatically generated by the 'createCnvEndianInput' script.
 * It contains the declarations of all CVs and TGT exports variables
 * and is used to generate the endian converters for all of these
 * variables.
 *
 * Generated on Mon Apr 22 15:38:32 PDT 2019
 */

#include "ksfse.global.h"
#include "ksfse.allcv.h"
#include "ksfse.tgtex.h"
